import {env} from 'cloudflare:workers';
import {NextResponse} from 'next/server';
import {session,sameOrigin} from '../../../lib/auth';
import {one,stmt,db,uid} from '../../../lib/db';
import {id} from '../../../lib/validation';
import {teamRoles,managementRoles,visibleTeamTask} from '../../../lib/team-work';
function bucket():R2Bucket{const storage=(env as unknown as {TEAM_FILES?:R2Bucket}).TEAM_FILES;if(!storage)throw new Error('File storage unavailable');return storage;}
const fail=(error:string,status=400)=>NextResponse.json({error},{status});
export async function GET(req:Request){try{const u=await session();if(!u)return fail('يجب تسجيل الدخول',401);if(!teamRoles.includes(u.role))return fail('غير مصرح',403);const file=await one('SELECT * FROM team_attachments WHERE id=? AND deleted_at IS NULL',id.parse(new URL(req.url).searchParams.get('id')));if(!file||!await visibleTeamTask(file.task_id,u))return fail('الملف غير متاح لك',403);const object=await bucket().get(file.object_key);if(!object)return fail('الملف غير متاح',404);return new Response(object.body,{headers:{'Content-Type':file.content_type,'Content-Disposition':"attachment; filename=\"download\"; filename*=UTF-8''"+encodeURIComponent(file.filename),'Content-Length':String(file.size),'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'"}});}catch(e){console.error(e);return fail('تعذر تحميل الملف',503);}}
export async function POST(req:Request){let objectKey='';try{if(!sameOrigin(req))return fail('طلب غير مسموح',403);const u=await session();if(!u)return fail('يجب تسجيل الدخول',401);if(!managementRoles.includes(u.role))return fail('غير مصرح',403);const length=Number(req.headers.get('content-length'));if(length>11*1024*1024)return fail('الحد الأقصى 10 ميجابايت للملف',413);const reader=req.body?.getReader();if(!reader)return fail('الملف مطلوب');const chunks:Uint8Array[]=[];let received=0;while(true){const part=await reader.read();if(part.done)break;received+=part.value.byteLength;if(received>11*1024*1024){await reader.cancel();return fail('الحد الأقصى 10 ميجابايت للملف',413);}chunks.push(part.value);}const bounded=new Uint8Array(received);let position=0;for(const chunk of chunks){bounded.set(chunk,position);position+=chunk.byteLength;}const parsed=new Request(req.url,{method:'POST',headers:req.headers,body:bounded});const form=await parsed.formData(),taskId=id.parse(form.get('taskId')),requestId=id.parse(form.get('requestId')),file=form.get('file');if(!(file instanceof File)||!file.size||file.size>10*1024*1024)return fail('الحد الأقصى 10 ميجابايت للملف');const task=await visibleTeamTask(taskId,u);if(!task||task.project_status==='ملغي')return fail('المهمة غير متاحة لك',403);const previous=await one('SELECT id,task_id,uploaded_by FROM team_attachments WHERE id=? AND deleted_at IS NULL',requestId);if(previous)return previous.task_id===taskId&&previous.uploaded_by===u.id?NextResponse.json({ok:true,id:previous.id}):fail('طلب مكرر مختلف',409);
const bytes=new Uint8Array(await file.arrayBuffer());const prefix=new TextDecoder().decode(bytes.slice(0,8));let contentType='';if(prefix.startsWith('%PDF-'))contentType='application/pdf';else if(bytes[0]===0x89&&prefix.slice(1,4)==='PNG'&&bytes[4]===13&&bytes[5]===10&&bytes[6]===26&&bytes[7]===10)contentType='image/png';else if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)contentType='image/jpeg';else if(prefix.startsWith('RIFF')&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP')contentType='image/webp';if(!contentType)return fail('المسموح PDF أو صور PNG وJPEG وWebP');const filename=file.name.replace(/[\u0000-\u001f\u007f/\\]/g,'_').slice(0,180)||'file';objectKey='team/'+taskId+'/'+uid();await bucket().put(objectKey,bytes,{httpMetadata:{contentType}});const at=new Date().toISOString();const result=await db().batch([stmt('INSERT INTO team_attachments(id,task_id,uploaded_by,filename,content_type,size,object_key,created_at) SELECT ?,?,?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM team_attachments WHERE task_id=? AND deleted_at IS NULL)<5 AND EXISTS(SELECT 1 FROM team_tasks WHERE id=? AND deleted_at IS NULL)',requestId,taskId,u.id,filename,contentType,file.size,objectKey,at,taskId,taskId),stmt('INSERT INTO audit_logs(id,user_id,entity,record_id,before_json,after_json,created_at) SELECT ?,?,?,?,?,?,? WHERE changes()>0',uid(),u.id,'teamAttachment',requestId,'{}',JSON.stringify({action:'upload',filename,taskId,projectId:task.project_id}),at)]);if(!result[0].meta.changes){await bucket().delete(objectKey);return fail('الحد الأقصى 5 ملفات لكل مهمة أو تم حذف المهمة');}objectKey='';return NextResponse.json({ok:true,id:requestId});}catch(e){if(objectKey)try{await bucket().delete(objectKey);}catch{}console.error(e);return fail('تعذر رفع الملف؛ حاول مرة أخرى',503);}}
export async function DELETE(req:Request){try{if(!sameOrigin(req))return fail('طلب غير مسموح',403);const u=await session();if(!u)return fail('يجب تسجيل الدخول',401);if(!managementRoles.includes(u.role))return fail('غير مصرح',403);const file=await one('SELECT * FROM team_attachments WHERE id=? AND deleted_at IS NULL',id.parse(new URL(req.url).searchParams.get('id')));if(!file||!await visibleTeamTask(file.task_id,u))return fail('الملف غير متاح',403);await bucket().delete(file.object_key);const at=new Date().toISOString();await db().batch([stmt('UPDATE team_attachments SET deleted_at=? WHERE id=?',at,file.id),stmt('INSERT INTO audit_logs(id,user_id,entity,record_id,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?)',uid(),u.id,'teamAttachment',file.id,'{}',JSON.stringify({action:'delete',filename:file.filename}),at)]);return NextResponse.json({ok:true});}catch(e){console.error(e);return fail('تعذر حذف الملف',503);}}
