'use client';
import {ForgotPassword} from '../password-reset';
import {useEffect,useState} from 'react';
import {FolderKanban,Headset,ShieldCheck,Eye,EyeOff} from 'lucide-react';
import {t,setLanguage,type Language} from '../../lib/i18n';
import ClientPortal from '../client-portal';
export default function ClientEntry(){const [lang,setLang]=useState<Language>('ar'),[user,setUser]=useState<any>(null),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[show,setShow]=useState(false);
function choose(next:Language){setLanguage(next);setLang(next);localStorage.setItem('raqamia-language',next);document.documentElement.lang=next;document.documentElement.dir=next==='ar'?'rtl':'ltr';document.title=next==='ar'?'raqamia tech | بوابة العميل':'raqamia tech | Client portal';}
useEffect(()=>{const saved=localStorage.getItem('raqamia-language');choose(saved==='en'?'en':'ar');fetch('/api/auth',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error();const b:any=await r.json();if(b.user?.role==='client')setUser(b.user);}).catch(()=>setError('تعذر الاتصال بالنظام')).finally(()=>setReady(true));},[]);
async function login(e:any){e.preventDefault();setError('');setBusy(true);try{const values=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,action:'login',portal:'client'})}),b:any=await r.json();if(!r.ok)throw new Error(b.error);if(b.user?.role!=='client')throw new Error('هذه الصفحة مخصصة لحسابات العملاء فقط');setUser(b.user);}catch(e:any){setError(e.message||'تعذر تسجيل الدخول');}finally{setBusy(false);}}
async function logout(){try{await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});}catch{}setUser(null);}
const languageButton=<button className="btn language-toggle" onClick={()=>choose(lang==='ar'?'en':'ar')}>{lang==='ar'?'English':'العربية'}</button>;
if(user)return <ClientPortal user={user} languageButton={languageButton} onLogout={logout}/>;
return <div className="client-entry" dir={lang==='ar'?'rtl':'ltr'}><header className="client-entry-header"><div className="client-entry-logo"><img className="brand-logo" src="/brand/raqamia-logo.png" width="210" height="73" alt="raqamia tech"/></div>{languageButton}</header><main className="client-entry-grid"><section className="client-welcome"><span className="client-kicker">{t('بوابة عملاء raqamia tech')}</span><h1>{t('موقعك بيتطور.')}<br/><em>{t('تابع كل خطوة.')}</em></h1><p>{t('كل تفاصيل مشروعك، آخر التحديثات، وفريق الدعم في مكان واحد.')}</p><div className="client-welcome-features"><div><FolderKanban size={23}/><span>{t('حالة المشروع ونسبة الإنجاز')}</span></div><div><Headset size={23}/><span>{t('طلبات دعم ومتابعة الردود')}</span></div><div><ShieldCheck size={23}/><span>{t('مساحة خاصة بمشاريعك')}</span></div></div></section><section className="client-login-card"><span className="client-login-icon"><FolderKanban size={26}/></span><h2>{t('أهلًا بيك في مساحة مشروعك')}</h2><p>{t('سجّل بالبيانات اللي أرسلها لك فريق raqamia tech.')}</p><form onSubmit={login}><label>{t('البريد الإلكتروني')}<input name="email" type="email" dir="ltr" required maxLength={200} autoComplete="username" placeholder="you@example.com"/></label><label>{t('كلمة المرور')}<span className="client-password"><input name="password" type={show?'text':'password'} dir="ltr" required minLength={12} maxLength={128} autoComplete="current-password"/><button type="button" className="icon-btn" onClick={()=>setShow(!show)} aria-label={t(show?'إخفاء كلمة المرور':'إظهار كلمة المرور')}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></label>{error&&<p className="error" role="alert">{t(error)}</p>}<button className="btn primary" disabled={busy||!ready}>{t(busy?'جارٍ تسجيل الدخول…':'الدخول لمشروعي')}</button></form><ForgotPassword portal="client"/></section></main><footer className="client-entry-footer">raqamia tech · {t('بوابة العميل')}</footer></div>;
}
