import {NextResponse} from 'next/server';
import {z} from 'zod';
import {session,sameOrigin,passwordHash} from '../../../lib/auth';
import {db,one,stmt,uid} from '../../../lib/db';
async function hash(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
async function limit(key:string,max:number){const at=Date.now(),cutoff=at-900000;const r:any=await stmt('INSERT INTO login_attempts(platform_id,attempts,window_start) VALUES(?,1,?) ON CONFLICT(platform_id) DO UPDATE SET attempts=CASE WHEN window_start<? THEN 1 ELSE attempts+1 END,window_start=CASE WHEN window_start<? THEN ? ELSE window_start END RETURNING attempts',key,at,cutoff,cutoff,at).first();return r.attempts<=max;}
const body=z.discriminatedUnion('action',[z.object({action:z.literal('generate'),currentPassword:z.string().min(12).max(128)}).strict(),z.object({action:z.literal('recover'),email:z.string().trim().toLowerCase().email().max(200),code:z.string().trim().max(100).transform(x=>x.replace(/[-\s]/g,'').toLowerCase()).pipe(z.string().regex(/^[a-f0-9]{64}$/)),password:z.string().min(12).max(128)}).strict()]);
const eligible="active=1 AND deleted_at IS NULL AND role='admin'";
export async function GET(){const u=await session();if(!u||u.role!=='admin')return NextResponse.json({error:'غير مصرح'},{status:403});const row=await one('SELECT created_at,used_at FROM admin_recovery WHERE user_id=?',u.id);return NextResponse.json({available:!!row&&!row.used_at,createdAt:row?.created_at||null},{headers:{'Cache-Control':'no-store'}});}
export async function POST(req:Request){try{if(!sameOrigin(req))return NextResponse.json({error:'طلب غير مسموح'},{status:403});const raw=await req.text();if(raw.length>2000)throw Error();const b=body.parse(JSON.parse(raw)),at=new Date().toISOString();
if(b.action==='generate'){const u=await session();if(!u||u.role!=='admin')return NextResponse.json({error:'غير مصرح'},{status:403});if(!await limit('recovery:generate:'+u.id,10))return NextResponse.json({error:'محاولات كثيرة، حاول بعد 15 دقيقة'},{status:429});const account=await one(`SELECT * FROM users WHERE id=? AND ${eligible}`,u.id);if(!account||await passwordHash(b.currentPassword,account.salt)!==account.password_hash)return NextResponse.json({error:'كلمة المرور الحالية غير صحيحة'},{status:400});const code=Array.from(crypto.getRandomValues(new Uint8Array(32))).map(x=>x.toString(16).padStart(2,'0')).join('');const result=await db().batch([stmt(`INSERT INTO admin_recovery(user_id,code_hash,created_at,used_at,operation_id) SELECT ?,?,?,NULL,NULL WHERE EXISTS(SELECT 1 FROM users WHERE id=? AND password_hash=? AND ${eligible}) ON CONFLICT(user_id) DO UPDATE SET code_hash=excluded.code_hash,created_at=excluded.created_at,used_at=NULL,operation_id=NULL`,u.id,await hash(code),at,u.id,account.password_hash)]);if(!result[0].meta.changes)throw Error();return NextResponse.json({code:code.match(/.{8}/g)!.join('-')},{headers:{'Cache-Control':'no-store'}});}
if(!await limit('recovery:ip:'+await hash(req.headers.get('cf-connecting-ip')||'unknown'),30)||!await limit('recovery:email:'+await hash(b.email),5))return NextResponse.json({error:'محاولات كثيرة، حاول بعد 15 دقيقة'},{status:429});const codeHash=await hash(b.code),account=await one(`SELECT u.id FROM users u JOIN admin_recovery r ON r.user_id=u.id WHERE lower(u.email)=? AND u.active=1 AND u.deleted_at IS NULL AND u.role='admin' AND r.code_hash=? AND r.used_at IS NULL`,b.email,codeHash);const invalid=()=>NextResponse.json({error:'البريد أو كود الاستعادة غير صحيح أو تم استخدامه'},{status:400});if(!account)return invalid();const salt=uid(),password=await passwordHash(b.password,salt),operation=uid();const result=await db().batch([stmt(`UPDATE admin_recovery SET used_at=?,operation_id=? WHERE user_id=? AND code_hash=? AND used_at IS NULL AND EXISTS(SELECT 1 FROM users WHERE id=admin_recovery.user_id AND lower(email)=? AND ${eligible})`,at,operation,account.id,codeHash,b.email),stmt('UPDATE users SET password_hash=?,salt=? WHERE id=? AND EXISTS(SELECT 1 FROM admin_recovery WHERE user_id=? AND operation_id=?)',password,salt,account.id,account.id,operation),stmt('DELETE FROM sessions WHERE user_id=? AND EXISTS(SELECT 1 FROM admin_recovery WHERE user_id=? AND operation_id=?)',account.id,account.id,operation),stmt("INSERT INTO audit_logs(id,user_id,entity,record_id,before_json,after_json,created_at) SELECT ?,?,'adminRecovery',?,'{}','{\"passwordReset\":true}',? WHERE EXISTS(SELECT 1 FROM admin_recovery WHERE user_id=? AND operation_id=?)",uid(),account.id,account.id,at,account.id,operation)]);if(!result[0].meta.changes)return invalid();return NextResponse.json({ok:true},{headers:{'Cache-Control':'no-store'}});
}catch{return NextResponse.json({error:'تحقق من البيانات؛ كلمة المرور 12 حرفًا على الأقل'},{status:400});}}
