import {NextResponse} from 'next/server';
import {z} from 'zod';
import {session,sameOrigin,passwordHash} from '../../../lib/auth';
import {db,rows,one,stmt,uid} from '../../../lib/db';
import {id,txt} from '../../../lib/validation';
import {agreementAt,commissionStatements,compensationGuard} from '../../../lib/sales-compensation';
import {today} from '../../../lib/db';
import {requireProgrammer} from '../../../lib/work-access';
const password=z.string().min(12).max(128);
const form=z.discriminatedUnion('action',[
z.object({action:z.literal('create'),name:txt,email:z.string().trim().email().max(200).transform(x=>x.toLowerCase()),password,role:z.enum(['programmer','manager','sales','employee']).default('programmer'),jobTitle:z.string().trim().max(200).default(''),replaceClient:z.boolean().default(false),reuseTeam:z.boolean().default(false)}).strict(),
z.object({action:z.literal('rename'),id,name:txt,email:z.string().trim().email().max(200).transform(x=>x.toLowerCase()),jobTitle:z.string().trim().max(200).default('')}).strict(),
z.object({action:z.literal('resetPassword'),id,password}).strict(),
z.object({action:z.literal('setActive'),id,active:z.boolean()}).strict(),
z.object({action:z.literal('deleteSales'),id}).strict(),
z.object({action:z.literal('saleOwner'),saleId:id,userId:z.union([id,z.literal('')])}).strict(),
z.object({action:z.literal('member'),projectId:id,userId:id,assigned:z.boolean()}).strict(),
z.object({action:z.literal('assignTask'),taskId:id,userId:z.union([id,z.literal('')]),version:z.number().int().nonnegative()}).strict()
]);
export async function GET(){try{const u=await session();if(!u)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});if(!['admin','manager'].includes(u.role))return NextResponse.json({error:'غير مصرح'},{status:403});return NextResponse.json({accounts:await rows("SELECT id,name,email,active,role,job_title,deleted_at FROM users WHERE role IN ('programmer','manager','sales','employee') AND (?='admin' OR role='programmer') ORDER BY role,name,email",u.role),members:await rows('SELECT m.project_id,m.user_id FROM project_members m JOIN projects p ON p.id=m.project_id')},{headers:{'Cache-Control':'no-store'}});}catch{return NextResponse.json({error:'تعذر تحميل حسابات الفريق'},{status:503});}}
export async function POST(req:Request){try{if(!sameOrigin(req))return NextResponse.json({error:'طلب غير مسموح'},{status:403});const u=await session();if(!u)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});if(!['admin','manager'].includes(u.role))return NextResponse.json({error:'غير مصرح'},{status:403});const b=form.parse(await req.json());if(u.role==='manager'&&b.action!=='member')return NextResponse.json({error:'غير مصرح'},{status:403});const batch:any[]=[];let recordId='',entity='programmerAccount',before:any={},after:any={},createdId:string|undefined;
if(b.action==='create'){const previous=await one('SELECT id,email,role,active,client_id,deleted_at FROM users WHERE lower(email)=?',b.email);if(previous){if(previous.role==='sales'||previous.deleted_at||b.role==='sales')return NextResponse.json({error:'هذا البريد مرتبط بحساب سابق. أنشئ حسابًا مستقلًا ببريد مختلف؛ سجل المبيعات يظل محفوظًا.',code:'SEPARATE_ACCOUNT'},{status:409});if(['programmer','manager','sales','employee'].includes(previous.role)){if(!b.reuseTeam)return NextResponse.json({error:'البريد مرتبط بحساب فريق موجود. اختر استخدام الحساب الحالي بالدور وكلمة المرور الجديدة.',code:'TEAM_EMAIL'},{status:409});const salt=uid(),hash=await passwordHash(b.password,salt),at=new Date().toISOString();const updates=[stmt("UPDATE users SET name=?,password_hash=?,salt=?,role=?,job_title=?,active=1 WHERE id=? AND deleted_at IS NULL AND role IN ('programmer','manager','sales','employee')",b.name,hash,salt,b.role,b.jobTitle,previous.id),stmt('DELETE FROM sessions WHERE user_id=?',previous.id)];if(previous.role==='programmer'&&b.role!=='programmer')updates.push(stmt('DELETE FROM project_members WHERE user_id=?',previous.id),stmt('UPDATE tasks SET assignee_id=NULL,version=version+1 WHERE assignee_id=?',previous.id),stmt('UPDATE team_tasks SET assignee_id=NULL,version=version+1,updated_at=? WHERE assignee_id=? AND deleted_at IS NULL',at,previous.id));updates.push(stmt('INSERT INTO audit_logs(id,user_id,entity,record_id,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?)',uid(),u.id,'programmerAccount',previous.id,JSON.stringify({role:previous.role,active:previous.active,email:previous.email}),JSON.stringify({action:'reuse',role:b.role,active:1,name:b.name,passwordReset:true}),at));await db().batch(updates);return NextResponse.json({ok:true,id:previous.id});}if(previous.role!=='client')return NextResponse.json({error:'هذا البريد مستخدم بالفعل'},{status:409});const client=previous.client_id?await one('SELECT id FROM clients WHERE id=?',previous.client_id):null;if(previous.active&&client&&!b.replaceClient)return NextResponse.json({error:'البريد مرتبط بحساب عميل. اختر استبدال حساب العميل بحساب الفريق للمتابعة.',code:'CLIENT_EMAIL'},{status:409});before={replacedClientAccount:{id:previous.id,email:previous.email,active:previous.active,clientId:previous.client_id}};const archived='archived-'+uid()+'@accounts.invalid';batch.push(stmt("UPDATE users SET email=?,active=0 WHERE id=? AND role='client' AND lower(email)=?",archived,previous.id,b.email),stmt('DELETE FROM sessions WHERE user_id=?',previous.id));}createdId=recordId=uid();const salt=uid(),hash=await passwordHash(b.password,salt);batch.push(stmt('INSERT INTO users(id,name,email,password_hash,salt,role,platform_id,job_title,active) VALUES(?,?,?,?,?,?,?,?,1)',recordId,b.name,b.email,hash,salt,b.role,'pending:'+recordId,b.jobTitle));after={name:b.name,email:b.email,role:b.role,active:1};}
if(['rename','resetPassword','setActive'].includes(b.action)){const v=b as any;const account=await one("SELECT id,name,email,active,role,job_title,deleted_at FROM users WHERE id=? AND deleted_at IS NULL AND role IN ('programmer','manager','sales','employee')",v.id);if(!account||account.deleted_at)return NextResponse.json({error:'حساب المبرمج غير موجود'},{status:404});recordId=v.id;before=account;after={...account};if(b.action==='rename'){if(await one('SELECT id FROM users WHERE lower(email)=? AND id<>?',b.email,b.id))throw new Error('هذا البريد مستخدم بالفعل');after={...account,name:b.name,email:b.email,job_title:b.jobTitle};batch.push(stmt("UPDATE users SET name=?,email=?,job_title=? WHERE id=? AND deleted_at IS NULL AND role IN ('programmer','manager','sales','employee')",b.name,b.email,b.jobTitle,b.id),stmt('DELETE FROM sessions WHERE user_id=?',b.id));}if(b.action==='resetPassword'){const salt=uid(),hash=await passwordHash(b.password,salt);after={passwordReset:true};batch.push(stmt("UPDATE users SET password_hash=?,salt=? WHERE id=? AND deleted_at IS NULL AND role IN ('programmer','manager','sales','employee')",hash,salt,b.id),stmt('DELETE FROM sessions WHERE user_id=?',b.id));}if(b.action==='setActive'){after.active=b.active?1:0;batch.push(stmt("UPDATE users SET active=? WHERE id=? AND deleted_at IS NULL AND role IN ('programmer','manager','sales','employee')",b.active?1:0,b.id));if(!b.active)batch.push(stmt('UPDATE sales_agreements SET end_month=? WHERE user_id=? AND (end_month IS NULL OR end_month>?)',today().slice(0,7),b.id,today().slice(0,7)),stmt('DELETE FROM sessions WHERE user_id=?',b.id),stmt('DELETE FROM project_members WHERE user_id=?',b.id),stmt('UPDATE team_tasks SET assignee_id=NULL,version=version+1 WHERE assignee_id=? AND deleted_at IS NULL',b.id),stmt('UPDATE tasks SET assignee_id=NULL,version=version+1 WHERE assignee_id=?',b.id));}}
if(b.action==='deleteSales'){const account=await one("SELECT id,name,email,role FROM users WHERE id=? AND role='sales' AND deleted_at IS NULL",b.id);if(!account)throw new Error('حساب السيلز غير موجود');recordId=b.id;entity='salesAccount';before=account;after={action:'delete',historyPreserved:true};batch.push(stmt("UPDATE users SET active=0,deleted_at=? WHERE id=? AND role='sales'",new Date().toISOString(),b.id),stmt('DELETE FROM sessions WHERE user_id=?',b.id),stmt('UPDATE sales_agreements SET end_month=? WHERE user_id=? AND (end_month IS NULL OR end_month>?)',today().slice(0,7),b.id,today().slice(0,7)));}
if(b.action==='saleOwner'){const sale=await one('SELECT s.*,p.id AS project_id FROM sales s JOIN projects p ON p.sale_id=s.id WHERE s.id=?',b.saleId);if(!sale)throw new Error('المشروع غير موجود');const previous=await one('SELECT * FROM sale_owners WHERE sale_id=?',b.saleId);if(previous?.user_id===b.userId)return NextResponse.json({ok:true});if(await one('SELECT id FROM expenses WHERE source=? AND paid_date IS NOT NULL','sales-commission:'+b.saleId))throw new Error('لا يمكن تغيير صاحب ديل تم سداد عمولته');let name='',rate=0,agreement:any=null;if(b.userId){const account=await one("SELECT id,name FROM users WHERE id=? AND role='sales' AND active=1 AND deleted_at IS NULL",b.userId);if(!account)throw new Error('حساب السيلز غير متاح');name=account.name;agreement=await agreementAt(b.userId,sale.date);rate=agreement?.rate||0;}recordId=b.saleId;entity='saleOwner';before=previous||{};after={userId:b.userId,rate};const guard=compensationGuard(u.id,'NOT EXISTS(SELECT 1 FROM expenses WHERE source=? AND paid_date IS NOT NULL)','sales-commission:'+b.saleId);batch.push(guard.check,b.userId?stmt('INSERT INTO sale_owners(sale_id,user_id,commission_rate,agreement_id) VALUES(?,?,?,?) ON CONFLICT(sale_id) DO UPDATE SET user_id=excluded.user_id,commission_rate=excluded.commission_rate,agreement_id=excluded.agreement_id',b.saleId,b.userId,rate,agreement?.id||null):stmt('DELETE FROM sale_owners WHERE sale_id=?',b.saleId),...commissionStatements(b.saleId,sale.project_id,sale.amount,sale.date,sale.status,rate,name),guard.clean);}
if(b.action==='member'){if(!await one('SELECT id FROM projects WHERE id=?',b.projectId))return NextResponse.json({error:'المشروع غير موجود'},{status:404});if(!await requireProgrammer(b.userId))return NextResponse.json({error:'حساب المبرمج غير متاح'},{status:400});recordId=b.projectId;entity='projectMember';after={userId:b.userId,assigned:b.assigned};if(b.assigned)batch.push(stmt("INSERT OR IGNORE INTO project_members(project_id,user_id) SELECT ?,id FROM users WHERE id=? AND role='programmer' AND active=1 AND EXISTS(SELECT 1 FROM projects WHERE id=?)",b.projectId,b.userId,b.projectId));else batch.push(stmt('UPDATE tasks SET assignee_id=NULL,version=version+1 WHERE project_id=? AND assignee_id=?',b.projectId,b.userId),stmt('UPDATE team_tasks SET assignee_id=NULL,version=version+1 WHERE project_id=? AND assignee_id=? AND deleted_at IS NULL',b.projectId,b.userId),stmt('DELETE FROM project_members WHERE project_id=? AND user_id=?',b.projectId,b.userId));}
if(b.action==='assignTask'){const task=await one('SELECT t.* FROM tasks t JOIN projects p ON p.id=t.project_id WHERE t.id=?',b.taskId);if(!task)return NextResponse.json({error:'السجل غير موجود'},{status:404});if(task.version!==b.version)return NextResponse.json({error:'تغيرت المهمة؛ حدّث البيانات وحاول مرة أخرى'},{status:409});if(b.userId&&(!await requireProgrammer(b.userId)||!await one('SELECT user_id FROM project_members WHERE project_id=? AND user_id=?',task.project_id,b.userId)))return NextResponse.json({error:'أسند المشروع للمبرمج أولًا'},{status:400});const result=await db().batch([stmt("UPDATE tasks SET assignee_id=?,version=version+1 WHERE id=? AND version=? AND EXISTS(SELECT 1 FROM projects WHERE id=tasks.project_id) AND (?='' OR EXISTS(SELECT 1 FROM project_members m JOIN users u ON u.id=m.user_id WHERE m.project_id=tasks.project_id AND m.user_id=? AND u.active=1 AND u.role='programmer'))",b.userId||null,b.taskId,b.version,b.userId,b.userId),stmt('INSERT INTO audit_logs(id,user_id,entity,record_id,before_json,after_json,created_at) SELECT ?,?,?,?,?,?,? WHERE changes()>0',uid(),u.id,'taskAssignee',b.taskId,JSON.stringify({assignee_id:task.assignee_id}),JSON.stringify({assignee_id:b.userId||null}),new Date().toISOString())]);if(!result[0].meta.changes)return NextResponse.json({error:'تغيرت المهمة؛ حدّث البيانات وحاول مرة أخرى'},{status:409});return NextResponse.json({ok:true});}
batch.push(stmt('INSERT INTO audit_logs(id,user_id,entity,record_id,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?)',uid(),u.id,entity,recordId,JSON.stringify(before),JSON.stringify(after),new Date().toISOString()));await db().batch(batch);return NextResponse.json({ok:true,id:createdId});
}catch(e:any){if(e instanceof z.ZodError)return NextResponse.json({error:'تحقق من الاسم والبريد وكلمة المرور والحقول المطلوبة'},{status:400});console.error(e);return NextResponse.json({error:'تعذر حفظ حساب الفريق أو الإسناد'},{status:400});}}
