import {NextResponse} from 'next/server';
import {cookies} from 'next/headers';
import {getChatGPTUser} from '../../chatgpt-auth';
import {session,passwordHash,issue,sameOrigin} from '../../../lib/auth';
import {one,db,uid} from '../../../lib/db';
async function digest(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
async function consume(key:string,max:number){const at=Date.now(),cutoff=at-900000;const row:any=await db().prepare('INSERT INTO login_attempts(platform_id,attempts,window_start) VALUES(?,1,?) ON CONFLICT(platform_id) DO UPDATE SET attempts=CASE WHEN window_start<? THEN 1 ELSE attempts+1 END,window_start=CASE WHEN window_start<? THEN ? ELSE window_start END RETURNING attempts').bind(key,at,cutoff,cutoff,at).first();return row.attempts<=max;}
export async function GET(){try{const p=await getChatGPTUser(),user=await session();const exists=await one('SELECT id FROM users LIMIT 1');return NextResponse.json({signedIn:!!user,user,setup:!exists&&!!p,email:p?.email||'',platform:true,hasPlatform:!!p},{headers:{'Cache-Control':'no-store'}});}catch{return NextResponse.json({error:'تعذر الاتصال بالنظام'},{status:503});}}
export async function POST(req:Request){try{if(!sameOrigin(req))return NextResponse.json({error:'طلب غير مسموح'},{status:403});const b:any=await req.json();if(b.action==='logout'){const token=(await cookies()).get('raqamia_session')?.value;if(token)await db().prepare('DELETE FROM sessions WHERE id=?').bind(token).run();(await cookies()).delete('raqamia_session');return NextResponse.json({ok:true});}
if(typeof b.email!=='string'||b.email.length>200||!/^\S+@\S+\.\S+$/.test(b.email.trim())||typeof b.password!=='string'||b.password.length<12||b.password.length>128)return NextResponse.json({error:'أدخل البريد وكلمة مرور من 12 حرفًا على الأقل'},{status:400});const email=b.email.trim().toLowerCase();const p=await getChatGPTUser();const exists=await one('SELECT id FROM users LIMIT 1');
if(b.action==='setup'&&!exists){if(!p)return NextResponse.json({error:'سجّل الدخول بحسابك أولًا'},{status:401});if(email!==p.email.toLowerCase())return NextResponse.json({error:'استخدم بريد حسابك الحالي لإنشاء المدير'},{status:400});const id=uid(),salt=uid(),hash=await passwordHash(b.password,salt);await db().prepare('INSERT INTO users(id,email,password_hash,salt,role,platform_id) SELECT ?,?,?,?,?,? WHERE NOT EXISTS(SELECT 1 FROM users)').bind(id,email,hash,salt,'admin',p.userId).run();const u=await one('SELECT id FROM users WHERE id=?',id);if(!u)return NextResponse.json({error:'تم إعداد الحساب بالفعل'},{status:409});await issue(id);return NextResponse.json({ok:true,user:{id,email,role:'admin',name:''}});}
const key='login:email:'+await digest(email);if(!await consume(key,10))return NextResponse.json({error:'محاولات كثيرة، حاول بعد 15 دقيقة'},{status:429});const ip=req.headers.get('cf-connecting-ip');if(ip&&!await consume('login:ip:'+await digest(ip),100))return NextResponse.json({error:'محاولات كثيرة، حاول بعد 15 دقيقة'},{status:429});const u=await one('SELECT * FROM users WHERE active=1 AND deleted_at IS NULL AND lower(email)=?',email);const hash=await passwordHash(b.password,u?.salt||'dummy-salt');let different=hash.length!==(u?.password_hash||'').length;for(let i=0;i<hash.length;i++)different=!!(Number(different)|(hash.charCodeAt(i)^(u?.password_hash||'').charCodeAt(i)));if(!u||different||!['admin','programmer','manager','sales','employee','client'].includes(u.role))return NextResponse.json({error:'بيانات الدخول غير صحيحة'},{status:401});
if(u.role==='client'&&(!u.client_id||!await one('SELECT id FROM clients WHERE id=?',u.client_id)))return NextResponse.json({error:'بيانات الدخول غير صحيحة'},{status:401});
if(b.portal==='client'&&u.role!=='client')return NextResponse.json({error:'هذه الصفحة مخصصة لحسابات العملاء فقط'},{status:403});
if(b.portal==='team'&&!['programmer','manager','employee'].includes(u.role)||b.portal==='sales'&&u.role!=='sales'||b.portal==='admin'&&u.role!=='admin')return NextResponse.json({error:'استخدم رابط الدخول الخاص بحسابك'},{status:403});
await db().prepare('DELETE FROM login_attempts WHERE platform_id=?').bind(key).run();await issue(u.id);return NextResponse.json({ok:true,user:{id:u.id,email:u.email,role:u.role,name:u.name,client_id:u.client_id}});
}catch{return NextResponse.json({error:'تعذر تسجيل الدخول، حاول مرة أخرى'},{status:500});}}
