import {NextResponse} from 'next/server';
import {z} from 'zod';
import {session,sameOrigin} from '../../../lib/auth';
import {rows,one,stmt,db,uid} from '../../../lib/db';
import {id} from '../../../lib/validation';
const text=z.string().trim().min(1).max(5000),status=z.enum(['open','in_progress','waiting_client','resolved']);
const form=z.discriminatedUnion('action',[
z.object({action:z.literal('create'),requestId:id,projectId:id,subject:z.string().trim().min(3).max(200),category:z.enum(['general','slow','outage','bug','change']),priority:z.enum(['normal','urgent']),body:text}).strict(),
z.object({action:z.literal('reply'),requestId:id,ticketId:id,body:text,status:status.optional()}).strict(),
z.object({action:z.literal('status'),ticketId:id,status}).strict()
]);
export async function GET(){try{const u=await session();if(!u)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});if(!['admin','manager','client','programmer'].includes(u.role))return NextResponse.json({error:'غير مصرح'},{status:403});const scope=u.role==='client'?' AND st.client_id=? AND s.client_id=st.client_id':u.role==='programmer'?' AND EXISTS(SELECT 1 FROM project_members pm WHERE pm.project_id=st.project_id AND pm.user_id=?)':'',args=u.role==='client'?[u.client_id]:u.role==='programmer'?[u.id]:[];const tickets=await rows('SELECT st.*,s.name AS project_name,c.name AS client_name FROM support_tickets st JOIN projects p ON p.id=st.project_id JOIN sales s ON s.id=p.sale_id JOIN clients c ON c.id=st.client_id WHERE 1=1'+scope+' ORDER BY st.updated_at DESC',...args);const messages=await rows("SELECT m.id,m.ticket_id,m.body,m.created_at,CASE WHEN u.role IN ('admin','manager','programmer') THEN 'admin' ELSE 'client' END AS author_role FROM support_messages m JOIN users u ON u.id=m.user_id JOIN support_tickets st ON st.id=m.ticket_id JOIN projects p ON p.id=st.project_id JOIN sales s ON s.id=p.sale_id JOIN clients c ON c.id=st.client_id WHERE 1=1"+scope+' ORDER BY m.created_at,m.rowid',...args);return NextResponse.json({tickets:tickets.map(ticket=>({id:ticket.id,project_id:ticket.project_id,project_name:ticket.project_name,client_name:ticket.client_name,subject:ticket.subject,category:ticket.category,priority:ticket.priority,status:ticket.status,created_at:ticket.created_at,updated_at:ticket.updated_at})),messages},{headers:{'Cache-Control':'no-store'}});}catch{return NextResponse.json({error:'تعذر تحميل طلبات الدعم'},{status:503});}}
export async function POST(req:Request){try{if(!sameOrigin(req))return NextResponse.json({error:'طلب غير مسموح'},{status:403});const u=await session();if(!u)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});if(!['admin','manager','client','programmer'].includes(u.role))return NextResponse.json({error:'غير مصرح'},{status:403});const raw=await req.text();if(raw.length>15000)return NextResponse.json({error:'الطلب كبير جدًا'},{status:413});const b=form.parse(JSON.parse(raw)),at=new Date().toISOString();
if(b.action==='create'){if(u.role!=='client')return NextResponse.json({error:'غير مصرح'},{status:403});const project=await one('SELECT p.id FROM projects p JOIN sales s ON s.id=p.sale_id JOIN clients c ON c.id=s.client_id WHERE p.id=? AND c.id=?',b.projectId,u.client_id);if(!project)return NextResponse.json({error:'المشروع غير متاح لك'},{status:403});const previous=await one('SELECT * FROM support_tickets WHERE id=?',b.requestId);if(previous){if(previous.created_by!==u.id||previous.subject!==b.subject||previous.project_id!==b.projectId||previous.category!==b.category||previous.priority!==b.priority||!(await one('SELECT id FROM support_messages WHERE ticket_id=? AND user_id=? AND body=? ORDER BY created_at LIMIT 1',previous.id,u.id,b.body)))return NextResponse.json({error:'طلب مكرر مختلف'},{status:409});return NextResponse.json({ok:true,id:previous.id});}const result=await db().batch([stmt("INSERT INTO support_tickets(id,project_id,client_id,created_by,subject,category,priority,status,created_at,updated_at) SELECT ?,?,?,?,?,?,?,'open',?,? WHERE (SELECT COUNT(*) FROM support_tickets WHERE created_by=? AND created_at>?)<10 AND EXISTS(SELECT 1 FROM projects p JOIN sales s ON s.id=p.sale_id JOIN clients c ON c.id=s.client_id WHERE p.id=? AND c.id=?)",b.requestId,b.projectId,u.client_id,u.id,b.subject,b.category,b.priority,at,at,u.id,new Date(Date.now()-86400000).toISOString(),b.projectId,u.client_id),stmt('INSERT INTO support_messages(id,ticket_id,user_id,body,created_at) SELECT ?,?,?,?,? WHERE changes()>0',uid(),b.requestId,u.id,b.body,at)]);if(!result[0].meta.changes)return NextResponse.json({error:'وصلت للحد اليومي لطلبات الدعم أو تغير المشروع'},{status:429});return NextResponse.json({ok:true,id:b.requestId});}
const ticket=await one('SELECT st.* FROM support_tickets st JOIN projects p ON p.id=st.project_id JOIN sales s ON s.id=p.sale_id JOIN clients c ON c.id=st.client_id WHERE st.id=?',b.ticketId);if(!ticket||u.role==='client'&&(ticket.client_id!==u.client_id||!await one('SELECT p.id FROM projects p JOIN sales s ON s.id=p.sale_id WHERE p.id=? AND s.client_id=?',ticket.project_id,u.client_id)))return NextResponse.json({error:'طلب الدعم غير متاح لك'},{status:403});
if(u.role==='programmer'&&!await one('SELECT user_id FROM project_members WHERE project_id=? AND user_id=?',ticket.project_id,u.id))return NextResponse.json({error:'طلب الدعم غير متاح لك'},{status:403});
if(b.action==='reply'&&b.status&&u.role==='client')return NextResponse.json({error:'غير مصرح'},{status:403});
if(b.action==='status'){if(!['admin','manager','programmer'].includes(u.role))return NextResponse.json({error:'غير مصرح'},{status:403});await db().batch([stmt('UPDATE support_tickets SET status=?,updated_at=? WHERE id=?',b.status,at,b.ticketId),stmt('INSERT INTO audit_logs(id,user_id,entity,record_id,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?)',uid(),u.id,'supportTicket',b.ticketId,JSON.stringify({status:ticket.status}),JSON.stringify({status:b.status}),at)]);}
if(b.action==='reply'){const previous=await one('SELECT id,ticket_id,user_id,body FROM support_messages WHERE id=?',b.requestId);if(previous){if(previous.ticket_id!==b.ticketId||previous.user_id!==u.id||previous.body!==b.body)return NextResponse.json({error:'طلب مكرر مختلف'},{status:409});return NextResponse.json({ok:true});}const recent=await one('SELECT COUNT(*) AS n FROM support_messages WHERE user_id=? AND created_at>?',u.id,new Date(Date.now()-3600000).toISOString());if(recent.n>=100)return NextResponse.json({error:'محاولات كثيرة، حاول لاحقًا'},{status:429});await db().batch([stmt('INSERT INTO support_messages(id,ticket_id,user_id,body,created_at) VALUES(?,?,?,?,?)',b.requestId,b.ticketId,u.id,b.body,at),stmt('UPDATE support_tickets SET updated_at=?,status=COALESCE(?,status) WHERE id=?',at,b.status||null,b.ticketId),...(b.status?[stmt('INSERT INTO audit_logs(id,user_id,entity,record_id,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?)',uid(),u.id,'supportTicket',b.ticketId,JSON.stringify({status:ticket.status}),JSON.stringify({status:b.status}),at)]:[])]);}
return NextResponse.json({ok:true});}catch{return NextResponse.json({error:'تعذر حفظ طلب الدعم؛ تحقق من الحقول وحاول مرة أخرى'},{status:400});}}
