'use client';
import {PasswordField} from './password-field';
import {AdminRecoverySettings} from './admin-recovery';
import {useState} from 'react';
import {ShieldCheck,Copy} from 'lucide-react';
import {t} from '../lib/i18n';
import {TeamAccounts} from './team-access';
import {ClientAccounts} from './portal-admin';
export default function AccountManagement({clients,user,onUserChange}:{clients:any[];user:any;onUserChange:(u:any)=>void}){const [tab,setTab]=useState('all'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const tabs=[['all','كل حسابات الشركة'],['programmer','المبرمجون'],['manager','التيم مانجر'],['sales','السيلز'],['employee','الموظفون'],['clients','حسابات العملاء'],['admin','حساب المدير']];
async function save(e:any){e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/account-profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))}),b:any=await r.json();if(!r.ok)throw Error(b.error);onUserChange(b.user);form.reset();setMessage('تم تحديث حساب المدير');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
return <><section className="panel padded account-entry-links">{[['/admin','دخول المدير'],['/team','دخول الفريق'],['/sales','دخول السيلز'],['/client','بوابة العميل']].map(([path,label])=><div key={path}><b>{t(label)}</b><a href={path} target="_blank" rel="noopener">{typeof window==='undefined'?path:window.location.origin+path}</a><button className="btn small" onClick={()=>navigator.clipboard.writeText(window.location.origin+path).then(()=>setMessage('تم نسخ رابط الدخول')).catch(()=>setError('تعذر نسخ الرابط'))}><Copy size={15}/>{t('نسخ الرابط')}</button></div>)}</section><div className="report-tabs">{tabs.map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>{setTab(key);setError('');setMessage('');}}>{t(label)}</button>)}</div>{error&&<p className="error" role="alert">{t(error)}</p>}{message&&<p className="info-box" role="status">{t(message)}</p>}{tab==='clients'?<ClientAccounts clients={clients}/>:tab==='admin'?<><section className="panel"><div className="panel-heading"><h2><ShieldCheck size={20}/> {t('حساب المدير')}</h2></div><form className="access-body" onSubmit={save} key={user.email}><div className="form-grid"><label>{t('الاسم')}<input name="name" defaultValue={user.name||'مدير الشركة'} required maxLength={200}/></label><label>{t('البريد الإلكتروني')}<input name="email" type="email" defaultValue={user.email} required maxLength={200} dir="ltr"/></label><label>{t('كلمة المرور الحالية')}<PasswordField name="currentPassword" minLength={12} maxLength={128} required autoComplete="current-password" dir="ltr"/></label><label>{t('كلمة مرور جديدة (اختياري)')}<PasswordField name="password" minLength={12} maxLength={128} autoComplete="new-password" dir="ltr"/></label></div><p className="footnote">{t('البريد خاص بالنظام ولا يشترط حساب ChatGPT. تعديل الحساب يسجّل خروج الأجهزة الأخرى.')}</p><button className="btn primary" disabled={busy}>{t(busy?'جارٍ الحفظ…':'حفظ البيانات')}</button></form></section><AdminRecoverySettings/></>:<TeamAccounts key={tab} roleFilter={tab}/>}</>;
}
