'use client';
import {WorkspaceHeader} from './workspace-header';
import {StaffSidebar} from './staff-sidebar';
import {SiteHealthPanel} from './site-health-panel';
import {useEffect,useState} from 'react';
import {FolderKanban,ListTodo,CheckCircle2,Clock,LogOut,RefreshCw,Menu,X,CalendarDays,UserRound,Search} from 'lucide-react';
import {t,enumText,locale} from '../lib/i18n';
import {usePageNavigation} from '../lib/page-navigation';
import {TeamWorkBoard} from './team-workspace';
import {SupportDesk} from './support-desk';
import {workLabels} from '../lib/work-access-labels';
const navigationPages=['overview','sites','projects','tasks','teamTasks','support'];
const count=(n:number)=>new Intl.NumberFormat(locale()).format(n);
export default function ProgrammerWorkspace({user,languageButton,onLogout}:{user:any;languageButton:React.ReactNode;onLogout:()=>void}){const [data,setData]=useState<any>({projects:[],tasks:[]}),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[mobile,setMobile]=useState(false),[query,setQuery]=useState(''),[online,setOnline]=useState(true);
const {page:view,setPage:setView,selected,setSelected}=usePageNavigation('programmer',navigationPages,'overview');
async function load(){setLoading(true);try{const r=await fetch('/api/work',{cache:'no-store'});const b:any=await r.json();if(!r.ok){if(r.status===401)onLogout();throw new Error(b.error);}setData(b);setError('');}catch(e:any){setError(e.message||'تعذر تحميل المشاريع والمهام');}finally{setLoading(false);}}
useEffect(()=>{load();setOnline(navigator.onLine);const online=()=>{setOnline(true);load();},offline=()=>setOnline(false);window.addEventListener('online',online);window.addEventListener('offline',offline);const timer=setInterval(()=>{if(navigator.onLine)load();},60000);return()=>{window.removeEventListener('online',online);window.removeEventListener('offline',offline);clearInterval(timer);};},[]);
async function update(task:any,status:string){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/work',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({taskId:task.id,status,version:task.version})});const b:any=await r.json();if(!r.ok)throw new Error(b.error);setMessage('تم تحديث حالة المهمة');await load();}catch(e:any){setError(e.message||'تعذر تحديث المهمة');if(navigator.onLine){try{const r=await fetch('/api/work',{cache:'no-store'});if(r.ok)setData(await r.json());}catch{}}}finally{setBusy(false);}}
const mine=data.tasks.filter((x:any)=>x.assignee_id===user.id),finished=mine.filter((x:any)=>x.done).length;const project=data.projects.find((p:any)=>p.id===selected);const visibleProjects=data.projects.filter((p:any)=>(p.name+' '+p.client).toLowerCase().includes(query.toLowerCase()));
function taskList(tasks:any[]){return tasks.length?<div className="table-scroll"><table><thead><tr>{['المهمة','المشروع','المبرمج المسؤول','الحالة','آخر تحديث'].map(h=><th key={h}>{t(h)}</th>)}</tr></thead><tbody>{tasks.map(task=>{const own=task.assignee_id===user.id,p=data.projects.find((p:any)=>p.id===task.project_id),cancelled=p?.status==='ملغي';return <tr key={task.id}><td className="cell-title">{task.name}</td><td><button className="text-btn" onClick={()=>{setView('projects');setSelected(task.project_id);}}>{p?.name}</button></td><td>{own?t('أنا'):task.assignee_name||t('غير مسندة')}</td><td>{own&&!cancelled?<select className="task-status-select" aria-label={t('حالة المهمة')+' · '+task.name} value={task.work_status} disabled={busy||!online} onChange={e=>update(task,e.target.value)}>{Object.entries(workLabels).map(([value,label])=><option key={value} value={value}>{t(label)}</option>)}</select>:<span className={'badge '+(task.done?'green':'amber')}>{t(workLabels[task.work_status])}</span>}</td><td>{task.updated_at?new Date(task.updated_at).toLocaleString(locale()):'—'}</td></tr>;})}</tbody></table></div>:<div className="empty"><ListTodo size={28}/><h3>{t('لا توجد مهام مسندة بعد')}</h3><p>{t('ستظهر مهامك هنا عندما يسندها المدير إليك.')}</p></div>;}
return <div className="app-shell programmer-shell staff-shell"><StaffSidebar user={user} title="مساحة المبرمج" menu={[["overview","يومي",ListTodo],["sites","حالة المواقع",FolderKanban],["projects","مشاريعي",FolderKanban],["tasks","مهامي",ListTodo],["teamTasks","تاسكات الفريق",ListTodo],["support","الدعم الفني",ListTodo]]} page={view} mobile={mobile} onClose={()=>setMobile(false)} onNavigate={key=>{setView(key);setSelected(null);setMobile(false);setQuery('');}} onLogout={onLogout}/>{mobile&&<div className="overlay" onClick={()=>setMobile(false)}/>}<div className="main"><WorkspaceHeader user={user} title="مساحة المبرمج" languageButton={languageButton} onMenu={()=>setMobile(true)} onNavigate={key=>{setView(key);setSelected(null);setMobile(false);}}/><main className="content">{!['sites','teamTasks','support'].includes(view)&&<div className="page-heading"><div><span className="eyebrow">raqamia tech</span><h1>{t(view==='overview'?'يومي':view==='sites'?'العناية بالمواقع':view==='teamTasks'?'تاسكات الفريق':view==='support'?'الدعم الفني':view==='tasks'?'مهامي':'مشاريعي')}</h1><p>{t('مشاريعك، مهامك، وتقدّم التنفيذ في مكان واحد.')}</p></div><button className="btn" onClick={load} disabled={loading||busy}><RefreshCw size={17}/>{t('تحديث البيانات')}</button></div>}{!online&&<p className="info-box" role="status">{t('أنت غير متصل. تحديث المهام يحتاج اتصالًا بالإنترنت.')}</p>}{error&&<p className="error" role="alert">{t(error)}</p>}{message&&<p className="info-box" role="status">{t(message)}</p>}{!['overview','sites'].includes(view)&&<div className="metrics programmer-metrics"><div className="metric"><div className="metric-top"><span>{t('مشاريعي')}</span><FolderKanban size={22}/></div><div className="metric-value">{count(data.projects.length)}</div></div><div className="metric"><div className="metric-top"><span>{t('مهام بانتظار الإنجاز')}</span><Clock size={22}/></div><div className="metric-value">{count(mine.length-finished)}</div></div><div className="metric green"><div className="metric-top"><span>{t('مهام مكتملة')}</span><CheckCircle2 size={22}/></div><div className="metric-value">{count(finished)}</div></div></div>}
{view==='overview'?<TeamWorkBoard programmer view="overview" onViewChange={()=>setView('teamTasks')}/>:view==='sites'?<SiteHealthPanel/>:view==='teamTasks'?<TeamWorkBoard programmer/>:view==='support'?<SupportDesk/>:loading&&data.projects.length===0?<div className="empty">{t('جارٍ التحميل…')}</div>:view==='tasks'?<section className="panel"><div className="panel-heading"><h2>{t('المهام المسندة إليّ')}</h2></div>{taskList(mine)}</section>:project?<><button className="text-btn back-projects" onClick={()=>setSelected(null)}>{t('العودة للمشاريع')}</button><section className="panel work-project-detail"><div className="panel-heading"><div><h2>{project.name}</h2><p>{project.client} · {enumText(project.service)}</p></div><span className="badge blue">{enumText(project.status)}</span></div><div className="work-detail-meta"><span>{t('البداية')}: <bdi>{project.start}</bdi></span><span>{t('التسليم')}: <bdi>{project.delivery}</bdi></span></div><div className="work-progress"><div><b>{t('تقدّم المشروع')}</b><span>{count(project.completed)} / {count(project.taskCount)} {t('مهمة')} · {count(project.progress)}%</span></div><progress value={project.progress} max={100} aria-label={t('تقدّم المشروع')}/><p className="footnote">{t('نسبة التقدّم تعتمد المهام المكتملة من إجمالي مهام المشروع.')}</p></div></section><section className="panel"><div className="panel-heading"><h2>{t('مهام المشروع')}</h2></div>{taskList(data.tasks.filter((x:any)=>x.project_id===project.id))}</section></>:<><label className="search-box work-search"><Search size={17}/><input placeholder={t('ابحث في مشاريعك…')} value={query} onChange={e=>setQuery(e.target.value)}/></label>{visibleProjects.length?<div className="work-project-grid">{visibleProjects.map((p:any)=><button type="button" className="panel work-project-card" key={p.id} onClick={()=>setSelected(p.id)}><div className="work-card-top"><FolderKanban size={24}/><span className="badge blue">{enumText(p.status)}</span></div><h2>{p.name}</h2><p>{p.client}</p><div className="work-card-dates"><span>{t('البداية')} <bdi>{p.start}</bdi></span><span>{t('التسليم')} <bdi>{p.delivery}</bdi></span></div><div className="work-progress"><div><span>{t('تقدّم المشروع')}</span><b>{count(p.progress)}%</b></div><progress value={p.progress} max={100}/><small>{count(p.completed)} / {count(p.taskCount)} {t('مهام مكتملة')}</small></div><span className="text-btn">{t('عرض المشروع')}</span></button>)}</div>:<div className="panel empty"><FolderKanban size={30}/><h3>{t('لا توجد مشاريع مسندة بعد')}</h3><p>{t('ستظهر مشاريعك هنا عندما يسندها المدير إليك.')}</p></div>}</>}
<footer className="app-footer"><span>raqamia tech</span><span>{t('نسبة التقدّم تعتمد المهام المكتملة من إجمالي مهام المشروع.')}</span></footer></main></div></div>;
}
