'use client';
import {ForgotPassword} from './password-reset';
import {useEffect,useState} from 'react';
import {FolderKanban,ListTodo,Users,ShoppingBag,ShieldCheck,Eye,EyeOff} from 'lucide-react';
import {t,setLanguage,type Language} from '../lib/i18n';
import ManagerWorkspace from './team-workspace';
import ProgrammerWorkspace from './programmer-workspace';
import SalesWorkspace from './sales-workspace';
export default function StaffEntry({portal}:{portal:'team'|'sales'}){const [lang,setLang]=useState<Language>('ar'),[user,setUser]=useState<any>(null),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[show,setShow]=useState(false);const allowed=portal==='sales'?['sales']:['manager','programmer','employee'];
function choose(next:Language){setLanguage(next);setLang(next);localStorage.setItem('raqamia-language',next);document.documentElement.lang=next;document.documentElement.dir=next==='ar'?'rtl':'ltr';}
useEffect(()=>{choose(localStorage.getItem('raqamia-language')==='en'?'en':'ar');fetch('/api/auth',{cache:'no-store'}).then(async r=>{const b:any=await r.json();if(!r.ok)throw Error(b.error);if(allowed.includes(b.user?.role))setUser(b.user);else if(b.signedIn)setError('استخدم رابط الدخول الخاص بحسابك');}).catch(e=>setError(e.message)).finally(()=>setReady(true));},[]);
async function login(e:any){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...Object.fromEntries(new FormData(e.currentTarget)),action:'login',portal})}),b:any=await r.json();if(!r.ok)throw Error(b.error);if(!allowed.includes(b.user?.role))throw Error('استخدم رابط الدخول الخاص بحسابك');setUser(b.user);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
async function logout(){await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});setUser(null);}
const languageButton=<button className="btn language-toggle" onClick={()=>choose(lang==='ar'?'en':'ar')}>{lang==='ar'?'English':'العربية'}</button>;
if(user?.role==='manager')return <ManagerWorkspace user={user} languageButton={languageButton} onLogout={logout}/>;
if(user?.role==='programmer')return <ProgrammerWorkspace user={user} languageButton={languageButton} onLogout={logout}/>;
if(user?.role==='sales')return <SalesWorkspace user={user} languageButton={languageButton} onLogout={logout}/>;
if(user)return <div className="content"><div className="page-heading"><div><h1>{user.name}</h1><p>{t('مساحة الفريق')} · {user.email}</p></div>{languageButton}<button className="btn" onClick={logout}>{t('تسجيل الخروج')}</button></div><section className="panel padded"><h2>{t('حسابك مفعّل')}</h2><p>{t('صلاحيات هذا الحساب تشمل الدخول لمساحة الفريق فقط. إسناد المشاريع والتاسكات متاح لحسابات المبرمجين.')}</p></section></div>;
return <div className="client-entry staff-entry" dir={lang==='ar'?'rtl':'ltr'}><header className="client-entry-header"><div className="client-entry-logo"><img className="brand-logo" src="/brand/raqamia-logo.png" width="210" height="73" alt="raqamia tech"/></div>{languageButton}</header><main className="client-entry-grid"><section className="client-welcome"><span className="client-kicker">{t(portal==='sales'?'بوابة فريق المبيعات':'بوابة فريق raqamia tech')}</span><h1>{t(portal==='sales'?'كل ديل.':'شغل الفريق.')}<br/><em>{t(portal==='sales'?'خطوة للنمو.':'في مكان واحد.')}</em></h1><p>{t(portal==='sales'?'سجّل العملاء والمبيعات، وتابع مشروعاتك والدفعات المستحقة.':'وزّع المشاريع، تابع التاسكات، وشارك الملفات مع فريقك.')}</p><div className="client-welcome-features"><div><FolderKanban size={23}/><span>{t('متابعة المشاريع')}</span></div><div>{portal==='sales'?<ShoppingBag size={23}/>:<ListTodo size={23}/>}<span>{t(portal==='sales'?'مبيعاتك وتحصيلاتك':'التاسكات والمرفقات')}</span></div><div><ShieldCheck size={23}/><span>{t('حساب مستقل بصلاحيات وظيفتك')}</span></div></div></section><section className="client-login-card"><span className="client-login-icon"><Users size={26}/></span><h2>{t(portal==='sales'?'أهلًا بفريق المبيعات':'أهلًا بفريق raqamia tech')}</h2><p>{t('سجّل بالبريد وكلمة المرور اللي أرسلهم لك مدير الشركة.')}</p><form onSubmit={login}><label>{t('البريد الإلكتروني')}<input name="email" type="email" dir="ltr" required maxLength={200} autoComplete="username"/></label><label>{t('كلمة المرور')}<span className="client-password"><input name="password" type={show?'text':'password'} dir="ltr" required minLength={12} maxLength={128} autoComplete="current-password"/><button type="button" className="icon-btn" onClick={()=>setShow(!show)} aria-label={t(show?'إخفاء كلمة المرور':'إظهار كلمة المرور')}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></span></label>{error&&<p className="error" role="alert">{t(error)}</p>}<button className="btn primary" disabled={busy||!ready}>{t(busy?'جارٍ تسجيل الدخول…':'تسجيل الدخول')}</button></form><ForgotPassword portal={portal}/><div className="staff-login-links"><a href="/team">{t('دخول الفريق')}</a><a href="/sales">{t('دخول السيلز')}</a><a href="/client">{t('بوابة العميل')}</a></div></section></main><footer className="client-entry-footer">raqamia tech · {t(portal==='sales'?'بوابة فريق المبيعات':'مساحة الفريق')}</footer></div>;
}
