import {commissionStatements,compensationGuard} from './sales-compensation';
import {commitMutation,MutationContext} from './sync-server';
import {db,one,rows,stmt,uid,today} from './db';
export async function editRecord(type:string,b:any,recordId:string,userId:string,ctx?:MutationContext,ids:any={}){
const table:Record<string,string>={client:'clients',sale:'sales',payment:'payments',expense:'expenses',design:'design_tasks',employee:'employees',task:'tasks'};
if(!table[type])throw new Error('هذا السجل لا يدعم التعديل');
const old=await one('SELECT * FROM '+table[type]+' WHERE id=?',recordId);if(!old)throw new Error('السجل غير موجود');
const batch:D1PreparedStatement[]=[];
const projectExists=async(p:string)=>{if(p&&!await one('SELECT id FROM projects WHERE id=?',p))throw new Error('المشروع غير موجود');};
const link=(expenseId:string,p:string|null)=>{batch.push(stmt('DELETE FROM project_costs WHERE expense_id=?',expenseId));if(p)batch.push(stmt('INSERT INTO project_costs(id,project_id,expense_id) VALUES(?,?,?)',uid(),p,expenseId));};
if(type==='client'){batch.push(stmt('UPDATE clients SET name=?,phone=?,email=? WHERE id=?',b.name,b.phone,b.email,recordId));old.projectStarts=[];for(const change of b.projectStarts||[]){const project=await one('SELECT p.*,s.delivery FROM projects p JOIN sales s ON s.id=p.sale_id WHERE p.id=? AND s.client_id=?',change.projectId,recordId);if(!project)throw new Error('المشروع غير مرتبط بهذا العميل');if(change.start>project.delivery)throw new Error('بداية المشروع بعد تاريخ التسليم');old.projectStarts.push({projectId:project.id,start:project.start});batch.push(stmt('UPDATE projects SET start=? WHERE id=?',change.start,change.projectId));}}
if(type==='sale'){
const p=await one('SELECT * FROM projects WHERE sale_id=?',recordId);const owner=await one('SELECT o.*,u.name FROM sale_owners o JOIN users u ON u.id=o.user_id WHERE o.sale_id=?',recordId);if(owner){const expense=await one('SELECT * FROM expenses WHERE source=?','sales-commission:'+recordId),value=b.status==='ملغي'?0:Math.round(b.amount*owner.commission_rate/10000);if(expense?.paid_date&&(expense.amount!==value||expense.date!==b.date))throw new Error('عمولة هذا الموقع مسددة؛ لا يمكن تغيير قيمتها أو تاريخها');const guard=compensationGuard(userId,'NOT EXISTS(SELECT 1 FROM expenses WHERE source=? AND paid_date IS NOT NULL AND (amount<>? OR date<>?))','sales-commission:'+recordId,value,b.date);batch.push(guard.check,...commissionStatements(recordId,p.id,b.amount,b.date,b.status,owner.commission_rate,owner.name),guard.clean);}const total=await one('SELECT COALESCE(SUM(amount),0) AS amount FROM payments WHERE sale_id=?',recordId);if(b.amount<total.amount)throw new Error('قيمة المشروع أقل من الدفعات المحصلة؛ صحح الدفعات أولًا');if(b.status==='ملغي'&&total.amount>0)throw new Error('لا يمكن إلغاء بيع عليه دفعات');
let clientId=b.clientId;if(clientId){if(!await one('SELECT id FROM clients WHERE id=?',clientId))throw new Error('العميل غير موجود');}
else {const matches=await rows('SELECT id FROM clients WHERE lower(trim(name))=lower(?)',b.clientName);if(matches.length>1)throw new Error('يوجد أكثر من عميل بهذا الاسم؛ استخدم اسمًا مميزًا');if(matches.length)clientId=matches[0].id;else {clientId=ids.client||uid();batch.push(stmt('INSERT INTO clients(id,name,phone,email,created) VALUES(?,?,?,?,?)',clientId,b.clientName,'','',today()));}}
batch.push(stmt("UPDATE sales SET client_id=?,name=?,service=?,amount=CASE WHEN ?>=COALESCE((SELECT SUM(amount) FROM payments WHERE sale_id=?),0) AND (?<>'ملغي' OR NOT EXISTS(SELECT 1 FROM payments WHERE sale_id=?)) THEN ? ELSE -1 END,date=?,delivery=?,status=? WHERE id=?",clientId,b.name,b.service,b.amount,recordId,b.status,recordId,b.amount,b.date,b.delivery,b.status,recordId),stmt('UPDATE projects SET responsible=?,start=? WHERE id=?',b.responsible,b.start||p.start,p.id));
const source='domain:'+recordId;const domain=await one('SELECT * FROM expenses WHERE source=?',source);if(domain||b.domainPrice>0){batch.push(stmt('INSERT INTO expenses(id,name,category,amount,date,project_id,source,notes) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(source) DO UPDATE SET paid_date=CASE WHEN expenses.deleted_at IS NOT NULL THEN NULL ELSE expenses.paid_date END,date=CASE WHEN expenses.deleted_at IS NOT NULL THEN excluded.date ELSE expenses.date END,deleted_at=NULL,amount=excluded.amount,name=excluded.name',ids.domain||uid(),'دومين: '+b.name,'Domains',b.domainPrice,b.date,p.id,source,'تكلفة الدومين ضمن سعر الموقع'),stmt('INSERT OR IGNORE INTO project_costs(id,project_id,expense_id) SELECT ?,?,id FROM expenses WHERE source=?',uid(),p.id,source));}
}
if(type==='payment'){const sale=await one('SELECT * FROM sales WHERE id=?',b.saleId);if(!sale||sale.status==='ملغي')throw new Error('المشروع غير متاح');const total=await one('SELECT COALESCE(SUM(amount),0) AS amount FROM payments WHERE sale_id=? AND id<>?',b.saleId,recordId);if(total.amount+b.amount>sale.amount)throw new Error('الدفعة تتجاوز المتبقي من قيمة المشروع');batch.push(stmt("UPDATE payments SET sale_id=?,amount=CASE WHEN ?+COALESCE((SELECT SUM(amount) FROM payments WHERE sale_id=? AND id<>?),0)<=(SELECT amount FROM sales WHERE id=?) AND (SELECT status FROM sales WHERE id=?)<>'ملغي' THEN ? ELSE -1 END,date=?,method=?,notes=? WHERE id=?",b.saleId,b.amount,b.saleId,recordId,b.saleId,b.saleId,b.amount,b.date,b.method,b.notes,recordId));}
if(type==='expense'){
const p=b.projectId||null;await projectExists(b.projectId);
if((old.source?.startsWith('sales-commission:')||old.source?.startsWith('sales-salary:'))&&(b.amount!==old.amount||b.date!==old.date||p!==old.project_id||b.category!==old.category))throw new Error('عدّل اتفاق السيلز أو قيمة الموقع من إدارة السيلز؛ هذا المصروف محسوب تلقائيًا');
if(old.source?.startsWith('design:'))throw new Error('عدّل تكلفة هذا المصروف من سجل التصميم');
if(old.source?.startsWith('domain:')&&(p!==old.project_id||b.category!=='Domains'))throw new Error('دومين المشروع يجب أن يبقى مرتبطًا بنفس المشروع وتصنيف الدومينات');
if(old.source?.startsWith('salary:')&&(p!==old.project_id||b.category!==old.category))throw new Error('عدّل قيمة أو تاريخ الراتب، مع الحفاظ على تصنيفه');
if(old.employee_id&&(p!==old.project_id||b.category!==old.category))throw new Error('الراتب مرتبط بعضو الفريق، حافظ على تصنيفه');
if(old.parent_id&&(b.amount!==old.amount||b.date!==old.date||p!==old.project_id||b.category!==old.category))throw new Error('عمولة الإعلان محسوبة تلقائيًا؛ عدّل الإعلان الأصلي لتصحيحها');
if(old.category==='Advertising'&&b.category!=='Advertising')throw new Error('هذا الإعلان مرتبط بعمولة؛ حافظ على تصنيف الإعلانات');
batch.push(stmt('UPDATE expenses SET name=?,category=?,amount=?,date=?,paid_date=?,project_id=?,notes=? WHERE id=?',b.name,b.category,b.amount,b.date,b.paidDate||null,p,b.notes,recordId));link(recordId,p);
if(b.category==='Advertising'){
const media=await one('SELECT * FROM expenses WHERE parent_id=?',recordId);const config=await one('SELECT * FROM settings WHERE effective<=? ORDER BY effective DESC,rowid DESC LIMIT 1',b.date)||await one('SELECT * FROM settings ORDER BY effective LIMIT 1');const rate=media?.rate??config.media;const commission=Math.round(b.amount*rate/10000);
if(media){if(media.paid_date&&media.paid_date<b.date)throw new Error('تاريخ الإعلان بعد سداد العمولة؛ صحح تاريخ سداد العمولة أولًا');batch.push(stmt('UPDATE expenses SET name=?,amount=?,date=?,project_id=? WHERE id=?','عمولة: '+b.name,commission,b.date,p,media.id));link(media.id,p);}
else {const m=ids.commission||uid();batch.push(stmt('INSERT INTO expenses(id,name,category,amount,date,project_id,notes,source,parent_id,rate) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(source) DO UPDATE SET deleted_at=NULL,amount=excluded.amount,date=excluded.date,project_id=excluded.project_id,paid_date=NULL,rate=excluded.rate,name=excluded.name,notes=excluded.notes',m,'عمولة: '+b.name,'Media Buyer',commission,b.date,p,'عمولة محسوبة تلقائيًا','media:'+recordId,recordId,rate));if(p){batch.push(stmt('DELETE FROM project_costs WHERE expense_id IN (SELECT id FROM expenses WHERE source=?)','media:'+recordId),stmt('INSERT INTO project_costs(id,project_id,expense_id) SELECT ?,?,id FROM expenses WHERE source=?',uid(),p,'media:'+recordId));}}
}}
if(type==='design'){await projectExists(b.projectId);const amount=b.count*b.price;if(amount>10000000000)throw new Error('تكلفة أعلى من الحد المسموح');batch.push(stmt('UPDATE design_tasks SET project_id=?,name=?,count=?,price=?,date=? WHERE id=?',b.projectId,b.name,b.count,b.price,b.date,recordId),stmt('UPDATE expenses SET name=?,amount=?,date=?,paid_date=?,project_id=? WHERE id=?',b.name,amount,b.date,b.paidDate||null,b.projectId,old.expense_id));link(old.expense_id,b.projectId);}
if(type==='employee'){if(b.startMonth!==old.start_month)throw new Error('شهر بداية الموظف محفوظ؛ يمكن تعديل اسمه ودوره وراتبه');batch.push(stmt('UPDATE employees SET name=?,role=?,type=?,amount=? WHERE id=?',b.name,b.role,b.contractType,b.amount,recordId));}
if(type==='task'){await projectExists(b.projectId);batch.push(stmt('UPDATE tasks SET name=?,assignee_id=CASE WHEN project_id=? THEN assignee_id ELSE NULL END,project_id=?,version=version+1 WHERE id=?',b.name,b.projectId,b.projectId,recordId));}
batch.push(stmt('INSERT INTO audit_logs(id,user_id,entity,record_id,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?)',uid(),userId,type,recordId,JSON.stringify(old),JSON.stringify(b),new Date().toISOString()));
const mappings:any={};if(type==='sale'&&ids.client){const existing=await one('SELECT id FROM clients WHERE lower(trim(name))=lower(?)',b.clientName);if(existing)mappings[ids.client]=existing.id;}for(const [key,source] of [['domain','domain:'+recordId],['commission','media:'+recordId]]){if(ids[key]){const existing:any=await db().prepare('SELECT id FROM expenses WHERE source=?').bind(source).first();if(existing)mappings[ids[key]]=existing.id;}}return await commitMutation(batch,{ok:true,id:recordId,mappings},ctx);
}
