import {schemas,today} from './validation';
export const recordTables:Record<string,string>={client:'clients',sale:'sales',project:'projects',payment:'payments',expense:'expenses',expensePaid:'expenses',design:'design_tasks',employee:'employees',employeeToggle:'employees',task:'tasks',taskToggle:'tasks',settings:'settings'};
export const newIds=()=>Object.fromEntries(['record','project','client','payment','domain','designTask','commission'].map(k=>[k,crypto.randomUUID()]));
export function deleteTree(data:any,type:string,id:string){const result:any={},queue:Array<[string,any]>=[];function add(t:string,r:any){if(!result[t])result[t]=[];if(!result[t].some((x:any)=>x.id===r.id)){result[t].push(r);queue.push([t,r]);}}function children(t:string,col:string,val:string){for(const r of data[t]||[])if(r[col]===val)add(t,r);}const t=recordTables[type],root=data[t]?.find((r:any)=>r.id===id);if(!root)throw new Error('السجل غير موجود');add(t,root);for(let i=0;i<queue.length;i++){const [t,r]=queue[i];if(t==='clients')children('sales','client_id',r.id);if(t==='sales'){children('projects','sale_id',r.id);children('payments','sale_id',r.id);}if(t==='projects'){children('sales','id',r.sale_id);children('expenses','project_id',r.id);children('design_tasks','project_id',r.id);children('tasks','project_id',r.id);}if(t==='expenses'){children('expenses','parent_id',r.id);children('design_tasks','expense_id',r.id);}if(t==='design_tasks')children('expenses','id',r.expense_id);if(t==='employees')children('expenses','employee_id',r.id);}return result;}
export function prepareBody(data:any,body:any){const b={...body,requestId:crypto.randomUUID(),creationIds:newIds(),operationDate:today(),operationAt:new Date().toISOString()};const table=recordTables[b.type];if(b.action==='edit'||b.action==='delete'||['project','expensePaid','taskToggle','employeeToggle'].includes(b.type)){b.expected=structuredClone(data[table]?.find((r:any)=>r.id===b.id));if(!b.expected)throw new Error('السجل غير موجود');}if(b.action==='delete')b.expectedTree=deleteTree(data,b.type,b.id);return b;}
export async function localMutation(original:any,body:any){const d=structuredClone(original),t=body.type,ids=body.creationIds;const find=(table:string,id:string)=>{const r=d[table]?.find((r:any)=>r.id===id);if(!r)throw new Error('السجل المرتبط غير موجود');return r;};const add=(table:string,r:any)=>{d[table].push({deleted_at:null,...r});return r;};const paid=(id:string,except?:string)=>d.payments.filter((p:any)=>p.sale_id===id&&p.id!==except).reduce((n:number,p:any)=>n+p.amount,0);const config=(date:string)=>[...d.settings].filter((s:any)=>s.effective<=date).sort((a:any,b:any)=>a.effective.localeCompare(b.effective)).at(-1)||d.settings[0];
if(body.action==='delete'){const root=d.expenses.find((e:any)=>e.id===body.id);if(t==='expense'&&(root?.source?.startsWith('sales-commission:')||root?.source?.startsWith('sales-salary:')))throw new Error('عدّل مستحق السيلز من إدارة السيلز');if(t==='settings'&&body.id==='initial')throw new Error('الإعدادات الأساسية لا تُحذف');const tree=deleteTree(d,t,body.id);d.deletedSources=d.deletedSources||[];for(const e of tree.expenses||[])if(e.source)d.deletedSources=[...new Set([...d.deletedSources,e.source])];for(const table of Object.keys(tree))d[table]=d[table].filter((r:any)=>!tree[table].some((x:any)=>x.id===r.id));return d;}
const b=schemas[t]?.parse(body);if(!b)throw new Error('عملية غير صالحة');const editing=body.action==='edit';const old=editing?find(recordTables[t],body.id):null;
const expense=(r:any)=>add('expenses',{paid_date:null,project_id:null,notes:'',source:null,parent_id:null,rate:null,employee_id:null,...r});
const client=()=>{if(b.clientId)return find('clients',b.clientId).id;const matches=d.clients.filter((c:any)=>c.name.trim().toLowerCase()===b.clientName.trim().toLowerCase());if(matches.length>1)throw new Error('يوجد أكثر من عميل بهذا الاسم');return matches[0]?.id||add('clients',{id:ids.client,name:b.clientName,phone:'',email:'',created:body.operationDate}).id;};
const domain=(s:any,p:any)=>{let e=d.expenses.find((e:any)=>e.source==='domain:'+s.id);if(e||b.domainPrice>0){if(!e)e=expense({id:ids.domain,name:'دومين: '+s.name,category:'Domains',amount:b.domainPrice,date:s.date,project_id:p.id,notes:'تكلفة الدومين ضمن سعر الموقع',source:'domain:'+s.id});else Object.assign(e,{amount:b.domainPrice,name:'دومين: '+s.name});}};
const salesCommission=(s:any)=>{const e=d.expenses.find((e:any)=>e.source==='sales-commission:'+s.id);if(!e)return;const value=s.status==='ملغي'?0:Math.round(s.amount*(e.rate||0)/10000);if(e.paid_date&&(e.amount!==value||e.date!==s.date))throw new Error('عمولة هذا الموقع مسددة؛ لا يمكن تغيير قيمتها أو تاريخها');if(!e.paid_date)Object.assign(e,{amount:value,date:s.date});};
if(t==='client'){if(editing){Object.assign(old,{name:b.name,phone:b.phone,email:b.email});for(const x of b.projectStarts){const p=find('projects',x.projectId),s=find('sales',p.sale_id);if(s.client_id!==old.id||x.start>s.delivery)throw new Error('تاريخ أو مشروع غير صالح');p.start=x.start;}}else add('clients',{id:ids.record,name:b.name,phone:b.phone,email:b.email,created:body.operationDate});}
if(t==='sale'){let s:any,p:any;if(editing){if(b.amount<paid(old.id))throw new Error('قيمة المشروع أقل من الدفعات المحصلة');if(b.status==='ملغي'&&paid(old.id))throw new Error('لا يمكن إلغاء بيع عليه دفعات');s=Object.assign(old,{client_id:client(),name:b.name,service:b.service,amount:b.amount,date:b.date,delivery:b.delivery,status:b.status});p=d.projects.find((p:any)=>p.sale_id===s.id);Object.assign(p,{start:b.start||p.start,responsible:b.responsible});}else{s=add('sales',{id:ids.record,client_id:client(),name:b.name,service:b.service,amount:b.amount,date:b.date,delivery:b.delivery,status:b.status});p=add('projects',{id:ids.project,sale_id:s.id,start:b.start||b.date,responsible:b.responsible});if(b.paid)add('payments',{id:ids.payment,sale_id:s.id,amount:b.paid,date:b.date,method:b.method,notes:''});}domain(s,p);salesCommission(s);}
if(t==='project'){const p=find('projects',b.id),s=find('sales',p.sale_id);if(b.delivery<b.start||b.delivery<(b.date||s.date))throw new Error('التسليم قبل البداية أو البيع');if(b.status==='ملغي'&&paid(s.id))throw new Error('لا يمكن إلغاء مشروع عليه دفعات');Object.assign(p,{start:b.start,responsible:b.responsible});Object.assign(s,{date:b.date||s.date,delivery:b.delivery,status:b.status});if(b.domainPrice!==undefined)domain(s,p);salesCommission(s);}
if(t==='payment'){const s=find('sales',b.saleId);if(s.status==='ملغي'||s.date>b.date||paid(s.id,old?.id)+b.amount>s.amount)throw new Error('تحقق من تاريخ الدفعة والمبلغ المتبقي');const r={sale_id:s.id,amount:b.amount,date:b.date,method:b.method,notes:b.notes};if(editing)Object.assign(old,r);else add('payments',{id:ids.record,...r});}
if(t==='expense'||t==='design'){if(b.projectId)find('projects',b.projectId);if(t==='design'){const amount=b.count*b.price;if(amount>10000000000)throw new Error('تكلفة أعلى من الحد المسموح');if(editing){Object.assign(old,{project_id:b.projectId,name:b.name,count:b.count,price:b.price,date:b.date});Object.assign(find('expenses',old.expense_id),{name:b.name,amount,date:b.date,paid_date:b.paidDate||null,project_id:b.projectId});}else{expense({id:ids.record,name:b.name,category:'Designer',amount,date:b.date,paid_date:b.paidDate||null,project_id:b.projectId,source:'design:'+ids.record});add('design_tasks',{id:ids.designTask,project_id:b.projectId,name:b.name,count:b.count,price:b.price,date:b.date,expense_id:ids.record});}}
else{if(!editing&&b.amount<=0)throw new Error('القيمة يجب أن تكون أكبر من صفر');if(editing){if((old.source?.startsWith('sales-commission:')||old.source?.startsWith('sales-salary:'))&&(b.amount!==old.amount||b.date!==old.date||(old.project_id||'')!==b.projectId||b.category!==old.category))throw new Error('عدّل مستحق السيلز من إدارة السيلز');if(old.source?.startsWith('design:'))throw new Error('عدّل تكلفة التصميم من سجل التصميم');if((old.source?.startsWith('domain:')||old.source?.startsWith('salary:')||old.employee_id)&&(old.category!==b.category||(old.project_id||'')!==b.projectId))throw new Error('حافظ على تصنيف وربط المصروف');if(old.parent_id&&(old.amount!==b.amount||old.date!==b.date||(old.project_id||'')!==b.projectId||old.category!==b.category))throw new Error('عدّل الإعلان الأصلي لتصحيح العمولة');if(old.category==='Advertising'&&b.category!=='Advertising')throw new Error('حافظ على تصنيف الإعلان');}
const e=editing?Object.assign(old,{name:b.name,category:b.category,amount:b.amount,date:b.date,paid_date:b.paidDate||null,project_id:b.projectId||null,notes:b.notes}):expense({id:ids.record,name:b.name,category:b.category,amount:b.amount,date:b.date,paid_date:b.paidDate||null,project_id:b.projectId||null,notes:b.notes});if(e.category==='Advertising'){const media=d.expenses.find((m:any)=>m.parent_id===e.id),rate=media?.rate??config(b.date).media,amount=Math.round(b.amount*rate/10000);if(media){if(media.paid_date&&media.paid_date<b.date)throw new Error('الإعلان بعد سداد العمولة');Object.assign(media,{name:'عمولة: '+b.name,amount,date:b.date,project_id:b.projectId||null});}else expense({id:ids.commission,name:'عمولة: '+b.name,category:'Media Buyer',amount,date:b.date,project_id:b.projectId||null,notes:'عمولة محسوبة تلقائيًا',source:'media:'+e.id,parent_id:e.id,rate});}}}
if(t==='expensePaid'){const e=find('expenses',b.id);if(e.paid_date||b.date<e.date)throw new Error('تاريخ السداد غير صالح أو المصروف مسدد بالفعل');e.paid_date=b.date;}
if(t==='task'){find('projects',b.projectId);if(editing)Object.assign(old,{name:b.name,assignee_id:old.project_id===b.projectId?(old.assignee_id||null):null,project_id:b.projectId,version:(old.version||0)+1});else add('tasks',{id:ids.record,project_id:b.projectId,name:b.name,done:0,work_status:'todo',version:0,assignee_id:null,updated_at:null});}
if(t==='taskToggle'){const task=find('tasks',b.id);Object.assign(task,{done:b.done?1:0,work_status:b.done?'done':'todo',version:(task.version||0)+1,updated_at:body.operationAt||null});}
if(t==='employee'){if(editing){if(b.startMonth!==old.start_month)throw new Error('شهر بداية الموظف محفوظ');Object.assign(old,{name:b.name,role:b.role,type:b.contractType,amount:b.amount});}else{if(b.startMonth<body.operationDate.slice(0,7))throw new Error('البدء من الشهر الحالي أو القادم');add('employees',{id:ids.record,name:b.name,role:b.role,type:b.contractType,amount:b.amount,active:1,start_month:b.startMonth});}}
if(t==='employeeToggle'){const e=find('employees',b.id);e.active=b.active?1:0;if(b.active)e.start_month=body.operationDate.slice(0,7);}
if(t==='settings'){if(b.effective.slice(0,7)<body.operationDate.slice(0,7)||b.effective.slice(8)!=='01'||b.startMonth!==d.settings.find((s:any)=>s.id==='initial').start_month)throw new Error('تاريخ سريان أو شهر بدء غير صالح');add('settings',{id:ids.record,effective:b.effective,content:b.content,programmer:b.programmer,designer:b.designer,media:b.media,currency:'EGP',start_month:b.startMonth,salaries_enabled:b.salariesEnabled?1:0,startup_reset_done:1});}
return d;
}
