import {localMutation,prepareBody} from './local-model';
import {accrueLocal} from './salary-model';
import {today} from './validation';
type Pending={id:string,body:any};type State={email:string,base:any,queue:Pending[],lastSync:string;shellReady?:boolean};type Envelope={email:string,salt:number[],iv:number[],cipher:number[]};
let key:CryptoKey|null=null;let account='';let serial=Promise.resolve();
async function database(){return await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('raqamia-offline-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('vault');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(new Error('تعذر فتح الحفظ المحلي على هذا المتصفح'));});}
async function readEnvelope():Promise<Envelope|undefined>{const db=await database();try{return await new Promise((resolve,reject)=>{const r=db.transaction('vault').objectStore('vault').get('current');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}finally{db.close();}}
async function writeEnvelope(e:Envelope){const db=await database();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction('vault','readwrite');tx.objectStore('vault').put(e,'current');tx.oncomplete=()=>resolve();tx.onabort=tx.onerror=()=>reject(new Error('لم تُحفظ البيانات محليًا؛ تحقق من مساحة الجهاز'));});}finally{db.close();}}
async function derive(password:string,salt:number[]){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return await crypto.subtle.deriveKey({name:'PBKDF2',salt:new Uint8Array(salt),iterations:250000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function decode(e:Envelope,k:CryptoKey):Promise<State>{return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(e.iv),additionalData:new TextEncoder().encode(e.email)},k,new Uint8Array(e.cipher))));}
async function read(){if(!key)throw new Error('افتح النسخة المحلية بكلمة المرور');const e=await readEnvelope();if(!e||e.email!==account)throw new Error('الحساب المحلي غير متاح');return await decode(e,key);}
async function write(state:State,salt?:number[]){if(!key)throw new Error('النسخة المحلية مقفلة');const previous=await readEnvelope(),iv=crypto.getRandomValues(new Uint8Array(12));const cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(state.email)},key,new TextEncoder().encode(JSON.stringify(state)));await writeEnvelope({email:state.email,salt:salt||previous!.salt,iv:[...iv],cipher:[...new Uint8Array(cipher)]});}
function exclusive<T>(fn:()=>Promise<T>):Promise<T>{const next=serial.then(async()=>{if(navigator.locks)return await navigator.locks.request('raqamia-financial-sync',async()=>await fn());return await fn();});serial=next.then(()=>undefined,()=>undefined);return next;}
async function view(s:State){let data=await accrueLocal(s.base,today());data.tasks=(data.tasks||[]).map((t:any)=>({assignee_id:null,work_status:t.done?'done':'todo',version:0,updated_at:null,...t}));for(const q of s.queue)data=await accrueLocal(await localMutation(data,q.body),today());return data;}
export async function offlineInfo(){const e=await readEnvelope();return{enabled:!!e,email:e?.email,unlocked:!!key};}
export async function enableOffline(email:string,password:string,data:any){return exclusive(async()=>{const old=await readEnvelope();account=email.trim().toLowerCase();if(old){if(old.email!==account)throw new Error('النسخة المحلية مرتبطة بحساب آخر');key=await derive(password,old.salt);try{await decode(old,key);}catch{key=null;throw new Error('كلمة مرور النسخة المحلية غير صحيحة');}return await offlineView();}const salt=[...crypto.getRandomValues(new Uint8Array(16))];key=await derive(password,salt);await write({email:account,base:data,queue:[],lastSync:new Date().toISOString()},salt);return await offlineView();});}
export async function unlockOffline(email:string,password:string){const e=await readEnvelope();if(!e||e.email!==email.trim().toLowerCase())throw new Error('لا توجد نسخة محلية لهذا الحساب');const candidate=await derive(password,e.salt);try{await decode(e,candidate);}catch{throw new Error('كلمة المرور غير صحيحة');}key=candidate;account=e.email;return await offlineView();}
export function lockOffline(){key=null;account='';}
export async function offlineView(){const s=await read();return{data:await view(s),queue:s.queue,lastSync:s.lastSync,email:s.email,shellReady:!!s.shellReady};}
export async function saveSnapshot(data:any,email:string){return exclusive(async()=>{const s=await read();if(s.email!==email.trim().toLowerCase())throw new Error('حساب المزامنة لا يطابق النسخة المحلية');if(s.queue.length)return await offlineView();s.base=data;s.lastSync=new Date().toISOString();await write(s);return await offlineView();});}
export async function queueMutation(body:any){return exclusive(async()=>{const s=await read(),data=await view(s),prepared=prepareBody(data,body);await localMutation(data,prepared);s.queue.push({id:prepared.requestId,body:prepared});await write(s);return await offlineView();});}
export class SyncError extends Error{constructor(message:string,public status:number){super(message);}}
async function remoteData(email:string){const auth=await fetch('/api/auth',{cache:'no-store'});let a:any;try{a=await auth.json();}catch{throw new SyncError('سجّل الدخول أونلاين لاستكمال المزامنة',401);}if(!auth.ok||!a.signedIn)throw new SyncError('سجّل الدخول أونلاين لاستكمال المزامنة',401);if(a.user?.email?.toLowerCase()!==email.toLowerCase())throw new SyncError('حساب السيرفر لا يطابق النسخة المحلية',403);const r=await fetch('/api/data',{cache:'no-store'});const b:any=await r.json();if(!r.ok)throw new SyncError(b.error||'تعذرت المزامنة',r.status);return b;}
function remap(value:any,mappings:any):any{if(typeof value==='string')return mappings[value]||value;if(Array.isArray(value))return value.map(v=>remap(v,mappings));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,remap(v,mappings)]));return value;}
export async function syncOffline(){return exclusive(async()=>{const s=await read();let latest=await remoteData(s.email);while(s.queue.length){const q=s.queue[0];const response=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(q.body)});let result:any;try{result=await response.json();}catch{throw new SyncError('تعذر التأكد من الحفظ؛ العملية محفوظة لإعادة المحاولة',503);}if(!response.ok)throw new SyncError(result.error||'تعذرت مزامنة العملية',response.status);s.base=await accrueLocal(await localMutation(s.base,q.body),today());s.queue.shift();if(result.mappings&&Object.keys(result.mappings).length){s.queue=s.queue.map(p=>({...p,body:remap(p.body,result.mappings)}));s.base=remap(s.base,result.mappings);}
// Commit acknowledgment before fetching: a lost GET must never resubmit an acknowledged payment.
await write(s);latest=await remoteData(s.email);s.base=latest;s.lastSync=new Date().toISOString();await write(s);}
s.base=latest;s.lastSync=new Date().toISOString();await write(s);return await offlineView();});}
export async function discardPending(){return exclusive(async()=>{const s=await read();s.base=await remoteData(s.email);s.queue=[];s.lastSync=new Date().toISOString();await write(s);return await offlineView();});}
export async function forgetOffline(){return exclusive(async()=>{const db=await database();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction('vault','readwrite');tx.objectStore('vault').delete('current');tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}finally{db.close();lockOffline();}});}
export async function prepareOfflineShell(){if(!('serviceWorker' in navigator))throw new Error('المتصفح لا يدعم تشغيل التطبيق دون إنترنت');const registration=await navigator.serviceWorker.register('/sw.js',{scope:'/'});await navigator.serviceWorker.ready;const worker=registration.active;if(!worker)throw new Error('أعد فتح التطبيق لإكمال تجهيز الأوفلاين');const urls=[...new Set(['/',...performance.getEntriesByType('resource').map((r:any)=>r.name).filter((u:string)=>{const url=new URL(u,location.href);return url.origin===location.origin&&(/\.(js|css|svg|woff2?)(\?|$)/.test(url.pathname));})])];await new Promise<void>((resolve,reject)=>{const channel=new MessageChannel(),timer=setTimeout(()=>reject(new Error('تعذر تجهيز كل ملفات الأوفلاين؛ حاول مرة أخرى')),30000);channel.port1.onmessage=e=>{clearTimeout(timer);e.data.ok?resolve():reject(new Error(e.data.error));};worker.postMessage({type:'PREPARE',urls},[channel.port2]);});if(navigator.storage?.persist)await navigator.storage.persist();}

export async function markShellReady(){return exclusive(async()=>{const s=await read();s.shellReady=true;await write(s);return await offlineView();});}
