import {env} from 'cloudflare:workers';
import {db,one,uid,stmt} from './db';
export async function digest(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
async function encryptionKey(){const secret=(env as any).SITE_CONNECTION_ENCRYPTION_KEY;if(!secret||secret.length<32)throw new Error('خدمة تشفير الربط غير جاهزة');return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret)),{name:'AES-GCM'},false,['encrypt','decrypt']);}
export async function encrypt(value:any,projectId:string){const iv=crypto.getRandomValues(new Uint8Array(12)),bytes=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(projectId)},await encryptionKey(),new TextEncoder().encode(JSON.stringify(value)));return JSON.stringify({iv:Array.from(iv),data:Array.from(new Uint8Array(bytes))});}
async function decrypt(value:string,projectId:string){const v=JSON.parse(value);return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(v.iv),additionalData:new TextEncoder().encode(projectId)},await encryptionKey(),new Uint8Array(v.data))));}
export function website(value:string){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password||u.port||u.pathname!=='/'||u.search||u.hash||!u.hostname.includes('.')||u.hostname==='localhost'||/^\d+[.:]/.test(u.hostname))throw new Error('أدخل رابط الموقع الأساسي باستخدام HTTPS');return u.origin;}
export function shopDomain(value:string){const domain=value.trim().toLowerCase().replace(/^https:\/\//,'').replace(/\/$/,'');if(!/^[a-z0-9][a-z0-9-]*\.myshopify\.com$/.test(domain)||domain.length>180)throw new Error('أدخل نطاق المتجر بصيغة name.myshopify.com');return domain;}
export function safeConnection(c:any){if(!c)return null;let payload:any={};try{payload=JSON.parse(c.payload);}catch{}return {provider:c.provider,site_url:c.site_url,last_seen:c.last_seen,status:c.status,active:!!c.active,payload};}
export async function audit(userId:string,entity:string,recordId:string,after:any){await stmt('INSERT INTO audit_logs(id,user_id,entity,record_id,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?)',uid(),userId,entity,recordId,'{}',JSON.stringify(after),new Date().toISOString()).run();}
async function remote(url:string,body:any,headers:any={}){const r=await fetch(url,{method:'POST',redirect:'manual',signal:AbortSignal.timeout(12000),headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)});if(!r.ok)throw new Error('remote');return r.json() as Promise<any>;}
export async function syncShopify(projectId:string){const c=await one("SELECT c.* FROM site_connections c JOIN projects p ON p.id=c.project_id JOIN sales s ON s.id=p.sale_id JOIN clients cl ON cl.id=s.client_id WHERE c.project_id=? AND c.provider='shopify' AND c.active=1",projectId);if(!c)throw new Error('الربط غير متاح');const at=Date.now();const lock=await stmt('UPDATE site_connections SET last_attempt=? WHERE project_id=? AND active=1 AND last_attempt<?',at,projectId,at-30000).run();if(!lock.meta.changes)throw new Error('انتظر 30 ثانية قبل تحديث الربط');try{const domain=shopDomain(c.site_url),credentials=await decrypt(c.credentials,projectId);let token=credentials.token;if(!token){const response=await fetch('https://'+domain+'/admin/oauth/access_token',{method:'POST',redirect:'manual',signal:AbortSignal.timeout(12000),headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'client_credentials',client_id:credentials.clientId,client_secret:credentials.clientSecret}).toString()});if(!response.ok)throw new Error('auth');const auth:any=await response.json();if(!auth.access_token)throw new Error('token');token=auth.access_token;}const result=await remote('https://'+domain+'/admin/api/2026-10/graphql.json',{query:'query RaqamiaSiteStatus { shop { name primaryDomain { url } } themes(first: 10) { nodes { name role } } }'},{'X-Shopify-Access-Token':token});if(result.errors||!result.data?.shop||!result.data?.themes)throw new Error('scope');const shop=result.data.shop;const main=result.data.themes.nodes.find((theme:any)=>theme.role==='MAIN');let url='';try{url=website(shop.primaryDomain.url);}catch{}const payload={name:String(shop.name).slice(0,200),url,theme:main?String(main.name).slice(0,200):'',platform:'Shopify'};await stmt("UPDATE site_connections SET payload=?,last_seen=?,status='connected' WHERE project_id=? AND credentials=? AND active=1",JSON.stringify(payload),new Date().toISOString(),projectId,c.credentials).run();return payload;}catch{await stmt("UPDATE site_connections SET status='error' WHERE project_id=? AND credentials=? AND active=1",projectId,c.credentials).run();throw new Error('تعذر الربط؛ راجع تثبيت التطبيق وصلاحية read_themes وبيانات الدخول');}}
