import {db,one} from './db';
export type MutationContext={id:string,userId:string,hash:string;guard?:D1PreparedStatement};
export function canonical(value:any):string{if(Array.isArray(value))return '['+value.map(canonical).join(',')+']';if(value&&typeof value==='object')return '{'+Object.keys(value).filter(k=>k!=='rowid'&&k!=='deleted_at').sort().map(k=>JSON.stringify(k)+':'+canonical(value[k])).join(',')+'}';return JSON.stringify(value);}
export async function mutationContext(body:any,userId:string):Promise<MutationContext|undefined>{if(!body.requestId)return;const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(body))))).map(x=>x.toString(16).padStart(2,'0')).join('');return{id:body.requestId,userId,hash};}
export async function previousMutation(ctx?:MutationContext){if(!ctx)return;const r=await one('SELECT * FROM mutation_receipts WHERE id=? AND user_id=?',ctx.id,ctx.userId);if(r){if(r.payload_hash!==ctx.hash)throw new Error('رقم العملية مستخدم لبيانات مختلفة');return JSON.parse(r.response_json);}}
export async function commitMutation(batch:D1PreparedStatement[],response:any,ctx?:MutationContext){if(ctx?.guard)batch.unshift(ctx.guard);if(ctx?.guard)batch.push(db().prepare('DELETE FROM mutation_receipts WHERE id=?').bind(ctx.id+':guard'));if(ctx)batch.push(db().prepare('INSERT INTO mutation_receipts(id,user_id,payload_hash,response_json,created_at) VALUES(?,?,?,?,?)').bind(ctx.id,ctx.userId,ctx.hash,JSON.stringify(response),new Date().toISOString()));try{await db().batch(batch);}catch(e){const previous=await previousMutation(ctx);if(previous)return previous;if(ctx?.guard&&String(e).includes('payload_hash'))conflict();throw e;}return response;}
export function conflict(){const e:any=new Error('تغيّر هذا السجل على السيرفر منذ آخر مزامنة. لم يتم استبدال البيانات؛ راجع التغييرات المعلقة.');e.status=409;throw e;}

export function guardExpected(ctx:MutationContext|undefined,table:string,row:any){if(!ctx)return;const columns=Object.keys(row).filter(k=>k!=='rowid');if(columns.some(k=>!/^[a-z_]+$/.test(k)))throw new Error('حقول غير صالحة');const predicate=columns.map(k=>k+' IS ?').join(' AND ');ctx.guard=db().prepare('INSERT INTO mutation_receipts(id,user_id,payload_hash,response_json,created_at) VALUES(?,?,CASE WHEN EXISTS(SELECT 1 FROM '+table+' WHERE '+predicate+') THEN ? ELSE NULL END,?,?)').bind(ctx.id+':guard',ctx.userId,...columns.map(k=>row[k]),'guard','{}',new Date().toISOString());}
