import {NextResponse} from 'next/server';
import {z} from 'zod';
import {session,sameOrigin} from '../../../lib/auth';
import {rows,one,stmt,db,uid,today} from '../../../lib/db';
import {initializeSalesSalaries,commissionStatements,compensationGuard} from '../../../lib/sales-compensation';
import {id} from '../../../lib/validation';
const month=z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/),date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v&&v<=today());
const form=z.discriminatedUnion('action',[z.object({action:z.literal('agreement'),requestId:id,userId:id,mode:z.enum(['salary','commission','both']),salary:z.coerce.number().finite().min(0).max(100000000).transform(n=>Math.round(n*100)),rate:z.coerce.number().finite().min(0).max(100).transform(n=>Math.round(n*100)),effectiveMonth:month,applyExisting:z.boolean().default(false)}).strict(),z.object({action:z.literal('paid'),id,date}).strict()]);
export async function GET(req:Request){try{const u=await session();if(!u)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});if(!['admin','sales'].includes(u.role))return NextResponse.json({error:'غير مصرح'},{status:403});const m=month.parse(new URL(req.url).searchParams.get('month')||today().slice(0,7)),admin=u.role==='admin';await initializeSalesSalaries();const accounts=await rows("SELECT id,name,email,active,deleted_at FROM users WHERE role='sales' "+(admin?'':'AND id=?')+' ORDER BY name',...(admin?[]:[u.id]));const agreements=await rows('SELECT * FROM sales_agreements '+(admin?'':'WHERE user_id=?')+' ORDER BY effective_month DESC,created_at DESC,rowid DESC',...(admin?[]:[u.id]));const deals=await rows("SELECT s.id,s.name,s.amount,s.date,s.status,o.user_id,o.commission_rate,c.name AS client,e.id AS expense_id,COALESCE(e.amount,0) AS commission,e.paid_date FROM sales s JOIN clients c ON c.id=s.client_id JOIN sale_owners o ON o.sale_id=s.id LEFT JOIN expenses e ON e.source='sales-commission:'||s.id WHERE substr(s.date,1,7)=? "+(admin?'':'AND o.user_id=?')+' ORDER BY s.date DESC',m,...(admin?[]:[u.id]));const salaries=await rows("SELECT e.id,e.amount,e.date,e.paid_date,u.id AS user_id FROM expenses e JOIN users u ON e.source='sales-salary:'||u.id||':'||? "+(admin?'':'WHERE u.id=?'),m,...(admin?[]:[u.id]));return NextResponse.json({month:m,accounts,agreements,deals,salaries},{headers:{'Cache-Control':'no-store'}});}catch{return NextResponse.json({error:'تعذر تحميل مستحقات السيلز'},{status:400});}}
export async function POST(req:Request){try{if(!sameOrigin(req))return NextResponse.json({error:'طلب غير مسموح'},{status:403});const u=await session();if(!u||u.role!=='admin')return NextResponse.json({error:'غير مصرح'},{status:403});const b=form.parse(await req.json());if(b.action==='paid'){const expense=await one("SELECT * FROM expenses WHERE id=? AND (source LIKE 'sales-salary:%' OR source LIKE 'sales-commission:%')",b.id);if(!expense||expense.amount<=0)throw Error('المستحق غير موجود');if(b.date<expense.date)throw Error('تاريخ السداد قبل الاستحقاق');if(expense.paid_date)return NextResponse.json({ok:true});await db().batch([stmt('UPDATE expenses SET paid_date=? WHERE id=? AND paid_date IS NULL',b.date,b.id),stmt('INSERT INTO audit_logs(id,user_id,entity,record_id,before_json,after_json,created_at) SELECT ?,?,?,?,?,?,? WHERE changes()>0',uid(),u.id,'salesPayment',b.id,JSON.stringify({paidDate:null}),JSON.stringify({paidDate:b.date}),new Date().toISOString())]);return NextResponse.json({ok:true});}
if(b.effectiveMonth<today().slice(0,7))throw Error('يبدأ الاتفاق من الشهر الحالي أو شهر قادم');const account=await one("SELECT id,name FROM users WHERE id=? AND role='sales' AND active=1 AND deleted_at IS NULL",b.userId);if(!account)throw Error('حساب السيلز غير متاح');const salary=b.mode==='commission'?0:b.salary,rate=b.mode==='salary'?0:b.rate;if((b.mode!=='commission'&&salary<=0)||(b.mode!=='salary'&&rate<=0))throw Error('أدخل المرتب أو نسبة العمولة حسب نوع الاتفاق');const existing=await one('SELECT * FROM sales_agreements WHERE id=?',b.requestId);if(existing){if(existing.user_id!==b.userId||existing.mode!==b.mode||existing.salary!==salary||existing.rate!==rate||existing.effective_month!==b.effectiveMonth)throw Error('رقم الاتفاق مستخدم لبيانات مختلفة');return NextResponse.json({ok:true});}const paidSalary=await one('SELECT amount FROM expenses WHERE source=? AND paid_date IS NOT NULL','sales-salary:'+b.userId+':'+b.effectiveMonth);if(paidSalary&&paidSalary.amount!==salary)throw Error('مرتب شهر السريان مسدد بالفعل؛ اختر شهرًا قادمًا لتغيير المرتب');const guard=compensationGuard(u.id,'NOT EXISTS(SELECT 1 FROM expenses WHERE source=? AND paid_date IS NOT NULL AND amount<>?)','sales-salary:'+b.userId+':'+b.effectiveMonth,salary);const at=new Date().toISOString(),batch=[guard.check,stmt('INSERT INTO sales_agreements(id,user_id,effective_month,mode,salary,rate,created_at) VALUES(?,?,?,?,?,?,?)',b.requestId,b.userId,b.effectiveMonth,b.mode,salary,rate,at),guard.clean];
if(b.applyExisting){const next=await one('SELECT MIN(effective_month) AS month FROM sales_agreements WHERE user_id=? AND effective_month>?',b.userId,b.effectiveMonth);const deals=await rows("SELECT s.*,p.id AS project_id FROM sales s JOIN projects p ON p.sale_id=s.id JOIN sale_owners o ON o.sale_id=s.id WHERE o.user_id=? AND substr(s.date,1,7)>=? AND (? IS NULL OR substr(s.date,1,7)<?) AND NOT EXISTS(SELECT 1 FROM expenses WHERE source='sales-commission:'||s.id AND paid_date IS NOT NULL)",b.userId,b.effectiveMonth,next.month,next.month);for(const sale of deals){const guard=compensationGuard(u.id,'EXISTS(SELECT 1 FROM sale_owners WHERE sale_id=? AND user_id=?) AND NOT EXISTS(SELECT 1 FROM expenses WHERE source=? AND paid_date IS NOT NULL)',sale.id,b.userId,'sales-commission:'+sale.id);batch.push(guard.check,stmt('UPDATE sale_owners SET commission_rate=?,agreement_id=? WHERE sale_id=? AND user_id=? AND NOT EXISTS(SELECT 1 FROM expenses WHERE source=? AND paid_date IS NOT NULL)',rate,b.requestId,sale.id,b.userId,'sales-commission:'+sale.id),...commissionStatements(sale.id,sale.project_id,sale.amount,sale.date,sale.status,rate,account.name),guard.clean);}}
batch.push(stmt('INSERT INTO audit_logs(id,user_id,entity,record_id,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?)',uid(),u.id,'salesAgreement',b.userId,'{}',JSON.stringify({mode:b.mode,salary,rate,effectiveMonth:b.effectiveMonth,applyExisting:b.applyExisting}),at));await db().batch(batch);await initializeSalesSalaries();return NextResponse.json({ok:true});}catch(e:any){return NextResponse.json({error:e instanceof z.ZodError?'تحقق من الاتفاق والمرتب والنسبة والتاريخ':/D1|SQL|constraint/i.test(e.message)?'تعذر حفظ مستحقات السيلز':e.message},{status:400});}}
