import { sqliteTable, text, integer, index, uniqueIndex, check } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
export const users=sqliteTable('users',{id:text('id').primaryKey(),email:text('email').notNull().unique(),passwordHash:text('password_hash').notNull(),salt:text('salt').notNull(),name:text('name').notNull().default(''),jobTitle:text('job_title').notNull().default(''),deletedAt:text('deleted_at'),active:integer('active').notNull().default(1),role:text('role').notNull().default('admin'),platformId:text('platform_id').notNull().unique(),clientId:text('client_id').references(()=>clients.id)});
export const sessions=sqliteTable('sessions',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),expires:integer('expires').notNull()});
export const clients=sqliteTable('clients',{deletedAt:text('deleted_at'),id:text('id').primaryKey(),name:text('name').notNull(),phone:text('phone').notNull().default(''),email:text('email').notNull().default(''),created:text('created').notNull()});
export const sales=sqliteTable('sales',{deletedAt:text('deleted_at'),id:text('id').primaryKey(),clientId:text('client_id').notNull().references(()=>clients.id),name:text('name').notNull(),service:text('service').notNull(),amount:integer('amount').notNull(),date:text('date').notNull(),delivery:text('delivery').notNull(),status:text('status').notNull().default('جديد')},t=>[index('sales_date').on(t.date),check('sale_amount',sql`${t.amount}>0`)]);
export const projects=sqliteTable('projects',{deletedAt:text('deleted_at'),id:text('id').primaryKey(),saleId:text('sale_id').notNull().unique().references(()=>sales.id),start:text('start').notNull(),responsible:text('responsible').notNull().default('')});
export const payments=sqliteTable('payments',{deletedAt:text('deleted_at'),id:text('id').primaryKey(),saleId:text('sale_id').notNull().references(()=>sales.id),amount:integer('amount').notNull(),date:text('date').notNull(),method:text('method').notNull(),notes:text('notes').notNull().default('')},t=>[index('payments_sale_date').on(t.saleId,t.date),check('payment_positive',sql`${t.amount}>0`)]);
export const employees=sqliteTable('employees',{deletedAt:text('deleted_at'),id:text('id').primaryKey(),name:text('name').notNull(),role:text('role').notNull(),type:text('type').notNull(),amount:integer('amount').notNull(),active:integer('active').notNull().default(1),startMonth:text('start_month').notNull()});
export const settings=sqliteTable('settings',{deletedAt:text('deleted_at'),id:text('id').primaryKey(),effective:text('effective').notNull(),content:integer('content').notNull(),programmer:integer('programmer').notNull(),designer:integer('designer').notNull(),media:integer('media').notNull(),currency:text('currency').notNull().default('EGP'),startMonth:text('start_month').notNull(),salariesEnabled:integer('salaries_enabled').notNull().default(0),startupResetDone:integer('startup_reset_done').notNull().default(0)});
export const expenses=sqliteTable('expenses',{deletedAt:text('deleted_at'),id:text('id').primaryKey(),name:text('name').notNull(),category:text('category').notNull(),amount:integer('amount').notNull(),date:text('date').notNull(),paidDate:text('paid_date'),projectId:text('project_id').references(()=>projects.id),notes:text('notes').notNull().default(''),source:text('source').unique(),parentId:text('parent_id'),rate:integer('rate'),employeeId:text('employee_id').references(()=>employees.id)},t=>[index('expenses_date').on(t.date),index('expenses_project').on(t.projectId),check('expense_nonnegative',sql`${t.amount}>=0`)]);
export const designTasks=sqliteTable('design_tasks',{deletedAt:text('deleted_at'),id:text('id').primaryKey(),projectId:text('project_id').notNull().references(()=>projects.id),name:text('name').notNull(),count:integer('count').notNull(),price:integer('price').notNull(),date:text('date').notNull(),expenseId:text('expense_id').notNull().unique().references(()=>expenses.id)});
export const projectCosts=sqliteTable('project_costs',{id:text('id').primaryKey(),projectId:text('project_id').notNull().references(()=>projects.id),expenseId:text('expense_id').notNull().unique().references(()=>expenses.id)});
export const tasks=sqliteTable('tasks',{deletedAt:text('deleted_at'),id:text('id').primaryKey(),projectId:text('project_id').notNull().references(()=>projects.id),name:text('name').notNull(),assigneeId:text('assignee_id').references(()=>users.id),workStatus:text('work_status').notNull().default('todo'),version:integer('version').notNull().default(0),updatedAt:text('updated_at'),done:integer('done').notNull().default(0)});
export const loginAttempts=sqliteTable('login_attempts',{platformId:text('platform_id').primaryKey(),attempts:integer('attempts').notNull().default(0),windowStart:integer('window_start').notNull()});
export const auditLogs=sqliteTable('audit_logs',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),entity:text('entity').notNull(),recordId:text('record_id').notNull(),beforeJson:text('before_json').notNull(),afterJson:text('after_json').notNull(),createdAt:text('created_at').notNull()},t=>[index('audit_created').on(t.createdAt)]);

export const mutationReceipts=sqliteTable('mutation_receipts',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),payloadHash:text('payload_hash').notNull(),responseJson:text('response_json').notNull(),createdAt:text('created_at').notNull()});

export const projectMembers=sqliteTable('project_members',{projectId:text('project_id').notNull().references(()=>projects.id),userId:text('user_id').notNull().references(()=>users.id)},t=>[uniqueIndex('project_members_unique').on(t.projectId,t.userId),index('project_members_user').on(t.userId,t.projectId)]);

export const projectPortal=sqliteTable('project_portal',{projectId:text('project_id').primaryKey().references(()=>projects.id),previewUrl:text('preview_url').notNull().default(''),notes:text('notes').notNull().default(''),sharedTasks:text('shared_tasks').notNull().default('[]')});
export const siteConnections=sqliteTable('site_connections',{projectId:text('project_id').primaryKey().references(()=>projects.id),provider:text('provider').notNull(),siteUrl:text('site_url').notNull(),keyHash:text('key_hash'),credentials:text('credentials'),payload:text('payload').notNull().default('{}'),lastSeen:text('last_seen'),lastAttempt:integer('last_attempt').notNull().default(0),status:text('status').notNull().default('pending'),active:integer('active').notNull().default(1)});
export const supportTickets=sqliteTable('support_tickets',{id:text('id').primaryKey(),projectId:text('project_id').notNull().references(()=>projects.id),clientId:text('client_id').notNull().references(()=>clients.id),createdBy:text('created_by').notNull().references(()=>users.id),subject:text('subject').notNull(),category:text('category').notNull(),priority:text('priority').notNull().default('normal'),status:text('status').notNull().default('open'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('tickets_client_updated').on(t.clientId,t.updatedAt),index('tickets_project').on(t.projectId)]);
export const supportMessages=sqliteTable('support_messages',{id:text('id').primaryKey(),ticketId:text('ticket_id').notNull().references(()=>supportTickets.id),userId:text('user_id').notNull().references(()=>users.id),body:text('body').notNull(),createdAt:text('created_at').notNull()},t=>[index('messages_ticket_created').on(t.ticketId,t.createdAt)]);

export const teamTasks=sqliteTable('team_tasks',{id:text('id').primaryKey(),projectId:text('project_id').notNull().references(()=>projects.id),assigneeId:text('assignee_id').references(()=>users.id),createdBy:text('created_by').notNull().references(()=>users.id),title:text('title').notNull(),description:text('description').notNull().default(''),dueDate:text('due_date').notNull().default(''),status:text('status').notNull().default('todo'),version:integer('version').notNull().default(0),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),deletedAt:text('deleted_at')},t=>[index('team_tasks_project_updated').on(t.projectId,t.updatedAt),index('team_tasks_assignee').on(t.assigneeId,t.projectId)]);
export const teamAttachments=sqliteTable('team_attachments',{id:text('id').primaryKey(),taskId:text('task_id').notNull().references(()=>teamTasks.id),uploadedBy:text('uploaded_by').notNull().references(()=>users.id),filename:text('filename').notNull(),contentType:text('content_type').notNull(),size:integer('size').notNull(),objectKey:text('object_key').notNull().unique(),createdAt:text('created_at').notNull(),deletedAt:text('deleted_at')},t=>[index('team_attachments_task').on(t.taskId)]);

export const saleOwners=sqliteTable('sale_owners',{commissionRate:integer('commission_rate').notNull().default(0),agreementId:text('agreement_id'),saleId:text('sale_id').primaryKey().references(()=>sales.id),userId:text('user_id').notNull().references(()=>users.id)},t=>[index('sale_owners_user').on(t.userId,t.saleId)]);
export const salesAgreements=sqliteTable('sales_agreements',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),effectiveMonth:text('effective_month').notNull(),endMonth:text('end_month'),mode:text('mode').notNull(),salary:integer('salary').notNull().default(0),rate:integer('rate').notNull().default(0),createdAt:text('created_at').notNull()},t=>[index('sales_agreements_user_month').on(t.userId,t.effectiveMonth)]);
export const passwordResetRequests=sqliteTable('password_reset_requests',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),portal:text('portal').notNull(),status:text('status').notNull().default('pending'),createdAt:text('created_at').notNull(),resolvedAt:text('resolved_at'),resolvedBy:text('resolved_by').references(()=>users.id),resolutionId:text('resolution_id')},t=>[uniqueIndex('password_reset_pending_user').on(t.userId).where(sql`${t.status}='pending'`),index('password_reset_status_created').on(t.status,t.createdAt)]);

export const adminRecovery=sqliteTable('admin_recovery',{userId:text('user_id').primaryKey().references(()=>users.id),codeHash:text('code_hash').notNull(),createdAt:text('created_at').notNull(),usedAt:text('used_at'),operationId:text('operation_id')});
