import {clientIp} from '../../../lib/auth';
import {NextResponse} from 'next/server';
import {z} from 'zod';
import {session,sameOrigin,passwordHash} from '../../../lib/auth';
import {db,one,rows,stmt,uid} from '../../../lib/db';
const requestBody=z.object({action:z.literal('request'),email:z.string().trim().toLowerCase().email().max(200),portal:z.enum(['client','sales','team'])}).strict();
const adminBody=z.discriminatedUnion('action',[z.object({action:z.literal('reset'),id:z.string().uuid(),password:z.string().min(12).max(128)}).strict(),z.object({action:z.literal('dismiss'),id:z.string().uuid()}).strict()]);
async function hash(value:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))).map(n=>n.toString(16).padStart(2,'0')).join('');}
async function limit(key:string,max:number){const at=Date.now(),cutoff=at-900000;const r:any=await db().prepare('INSERT INTO login_attempts(platform_id,attempts,window_start) VALUES(?,1,?) ON CONFLICT(platform_id) DO UPDATE SET attempts=CASE WHEN window_start<? THEN 1 ELSE attempts+1 END,window_start=CASE WHEN window_start<? THEN ? ELSE window_start END RETURNING attempts').bind(key,at,cutoff,cutoff,at).first();return r.attempts<=max;}
const eligible="u.active=1 AND u.deleted_at IS NULL AND u.role IN ('client','sales','manager','programmer','employee') AND (u.role!='client' OR EXISTS(SELECT 1 FROM clients c WHERE c.id=u.client_id))";
export async function GET(){try{const u=await session();if(!u)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});if(u.role!=='admin')return NextResponse.json({error:'غير مصرح'},{status:403});const list=await rows(`SELECT r.id,r.portal,r.created_at,u.name,u.email,u.role,CASE WHEN ${eligible} THEN 1 ELSE 0 END AS available FROM password_reset_requests r JOIN users u ON u.id=r.user_id WHERE r.status='pending' ORDER BY r.created_at ASC LIMIT 100`);const count=await one("SELECT COUNT(*) AS n FROM password_reset_requests WHERE status='pending'");return NextResponse.json({requests:list,total:count.n},{headers:{'Cache-Control':'no-store'}});}catch{return NextResponse.json({error:'تعذر تحميل طلبات كلمة المرور'},{status:503});}}
export async function POST(req:Request){try{if(!sameOrigin(req))return NextResponse.json({error:'طلب غير مسموح'},{status:403});const raw=await req.text();if(raw.length>2000)return NextResponse.json({error:'طلب غير صالح'},{status:400});const input=JSON.parse(raw);if(input.action==='request'){const b=requestBody.parse(input),ip=clientIp(req)||'unknown';if(!await limit('reset:ip:'+await hash(ip),20)||!await limit('reset:email:'+await hash(b.email),3))return NextResponse.json({error:'محاولات كثيرة، حاول بعد 15 دقيقة'},{status:429});const user=await one(`SELECT u.id,u.role FROM users u WHERE lower(u.email)=? AND ${eligible}`,b.email);const matches=user&&(b.portal==='client'?user.role==='client':b.portal==='sales'?user.role==='sales':['manager','programmer','employee'].includes(user.role));if(matches)await stmt("INSERT INTO password_reset_requests(id,user_id,portal,status,created_at) VALUES(?,?,?,'pending',?) ON CONFLICT DO NOTHING",uid(),user.id,b.portal,new Date().toISOString()).run();return NextResponse.json({ok:true,message:'إذا كان البريد مرتبطًا بحساب في هذه البوابة، سيصل طلبك إلى مدير النظام.'},{headers:{'Cache-Control':'no-store'}});}
const admin=await session();if(!admin)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});if(admin.role!=='admin')return NextResponse.json({error:'غير مصرح'},{status:403});const b=adminBody.parse(input),at=new Date().toISOString(),operation=uid();if(b.action==='dismiss'){const result=await stmt("UPDATE password_reset_requests SET status='dismissed',resolved_at=?,resolved_by=?,resolution_id=? WHERE id=? AND status='pending'",at,admin.id,operation,b.id).run();if(!result.meta.changes)return NextResponse.json({error:'تم التعامل مع الطلب بالفعل'},{status:409});return NextResponse.json({ok:true});}
const request=await one(`SELECT r.user_id FROM password_reset_requests r JOIN users u ON u.id=r.user_id WHERE r.id=? AND r.status='pending' AND ${eligible}`,b.id);if(!request)return NextResponse.json({error:'الطلب أو الحساب غير متاح'},{status:409});const salt=uid(),password=await passwordHash(b.password,salt);const result=await db().batch([stmt(`UPDATE password_reset_requests SET status='resolved',resolved_at=?,resolved_by=?,resolution_id=? WHERE id=? AND status='pending' AND EXISTS(SELECT 1 FROM users u WHERE u.id=password_reset_requests.user_id AND ${eligible})`,at,admin.id,operation,b.id),stmt('UPDATE users SET password_hash=?,salt=? WHERE id=? AND EXISTS(SELECT 1 FROM password_reset_requests WHERE id=? AND resolution_id=?)',password,salt,request.user_id,b.id,operation),stmt('DELETE FROM sessions WHERE user_id=? AND EXISTS(SELECT 1 FROM password_reset_requests WHERE id=? AND resolution_id=?)',request.user_id,b.id,operation),stmt('INSERT INTO audit_logs(id,user_id,entity,record_id,before_json,after_json,created_at) SELECT ?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM password_reset_requests WHERE id=? AND resolution_id=?)',uid(),admin.id,'passwordReset',request.user_id,'{}',JSON.stringify({requestId:b.id,action:'reset'}),at,b.id,operation)]);if(!result[0].meta.changes)return NextResponse.json({error:'تم التعامل مع الطلب بالفعل'},{status:409});return NextResponse.json({ok:true});}catch{return NextResponse.json({error:'تحقق من البيانات؛ كلمة المرور 12 حرفًا على الأقل'},{status:400});}}
