import {NextResponse} from 'next/server';
import {session} from '../../../lib/auth';
import {rows} from '../../../lib/db';
export async function GET(){try{const u=await session();if(!u)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});const items:any[]=[];const add=(list:any[],kind:string,page:string)=>list.forEach(x=>items.push({id:kind+':'+x.id,title:x.title,detail:x.detail||'',page,date:x.date||'',kind}));
if(['admin','manager','programmer'].includes(u.role)){const own=u.role==='programmer';add(await rows(`SELECT tt.id,tt.title,s.name AS detail,tt.updated_at AS date FROM team_tasks tt JOIN projects p ON p.id=tt.project_id JOIN sales s ON s.id=p.sale_id WHERE tt.deleted_at IS NULL AND tt.status!='done' ${own?"AND tt.assignee_id=? AND EXISTS(SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=?)":''} ORDER BY tt.updated_at DESC LIMIT 20`,...(own?[u.id,u.id]:[])),'task',u.role==='admin'?'teamManagement':u.role==='manager'?'tasks':'teamTasks');}
if(u.role==='programmer')add(await rows("SELECT t.id,t.name AS title,s.name AS detail,t.updated_at AS date FROM tasks t JOIN projects p ON p.id=t.project_id JOIN sales s ON s.id=p.sale_id WHERE t.assignee_id=? AND t.done=0 AND EXISTS(SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=?) ORDER BY t.updated_at DESC LIMIT 20",u.id,u.id),'task','tasks');
if(['admin','manager','programmer','client'].includes(u.role)){const scope=u.role==='client'?' AND st.client_id=? AND s.client_id=st.client_id':u.role==='programmer'?' AND EXISTS(SELECT 1 FROM project_members pm WHERE pm.project_id=p.id AND pm.user_id=?)':'';add(await rows(`SELECT st.id,st.subject AS title,s.name AS detail,st.updated_at AS date FROM support_tickets st JOIN projects p ON p.id=st.project_id JOIN sales s ON s.id=p.sale_id JOIN clients c ON c.id=st.client_id WHERE st.status!='resolved' ${scope} ORDER BY st.updated_at DESC LIMIT 20`,...(u.role==='client'?[u.client_id]:u.role==='programmer'?[u.id]:[])),'support','support');}
if(u.role==='sales')add(await rows("SELECT s.id,s.name AS title,c.name AS detail,s.date AS date FROM sales s JOIN sale_owners so ON so.sale_id=s.id JOIN clients c ON c.id=s.client_id WHERE so.user_id=? AND s.status NOT IN ('تم التسليم','ملغي') ORDER BY s.date DESC LIMIT 20",u.id),'sale','projects');
if(u.role==='admin')add(await rows("SELECT r.id,u.name AS title,'طلب تغيير كلمة المرور' AS detail,r.created_at AS date FROM password_reset_requests r JOIN users u ON u.id=r.user_id WHERE r.status='pending' ORDER BY r.created_at DESC LIMIT 20"),'reset','accounts');
return NextResponse.json({items:items.sort((a,b)=>b.date.localeCompare(a.date)).slice(0,50)},{headers:{'Cache-Control':'no-store'}});}catch{return NextResponse.json({error:'تعذر تحميل الإشعارات'},{status:503});}}
