import {NextResponse} from 'next/server';
import {z} from 'zod';
import {session,sameOrigin,passwordHash} from '../../../lib/auth';
import {db,rows,one,stmt,uid} from '../../../lib/db';
import {id,txt} from '../../../lib/validation';
import {audit,digest,encrypt,website,shopDomain,safeConnection,syncShopify} from '../../../lib/site-connections';
const pass=z.string().min(12).max(128),secret=z.string().trim().min(10).max(500),url=z.string().trim().max(500).refine(v=>!v||(/^https:\/\//.test(v)&&!new URL(v).username&&!new URL(v).password),'HTTPS required');
const form=z.discriminatedUnion('action',[
z.object({action:z.literal('create'),clientId:id,email:z.string().trim().email().max(200).transform(v=>v.toLowerCase()),password:pass}).strict(),
z.object({action:z.literal('resetPassword'),id,password:pass}).strict(),z.object({action:z.literal('editAccount'),id,name:txt,email:z.string().trim().email().max(200).transform(x=>x.toLowerCase())}).strict(),z.object({action:z.literal('setActive'),id,active:z.boolean()}).strict(),
z.object({action:z.literal('portal'),projectId:id,previewUrl:url,notes:z.string().trim().max(4000),sharedTasks:z.array(id).max(1000)}).strict(),
z.object({action:z.literal('wordpress'),projectId:id,siteUrl:z.string().max(500)}).strict(),
z.object({action:z.literal('shopify'),projectId:id,domain:z.string().max(200),mode:z.enum(['credentials','token']),clientId:z.string().trim().max(500).optional(),clientSecret:secret.optional(),token:secret.optional()}).strict(),
z.object({action:z.literal('sync'),projectId:id}).strict(),z.object({action:z.literal('revoke'),projectId:id}).strict()
]);
export async function GET(){try{const u=await session();if(!u)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});if(u.role!=='admin')return NextResponse.json({error:'غير مصرح'},{status:403});return NextResponse.json({accounts:await rows("SELECT u.id,u.name,u.email,u.active,u.client_id FROM users u JOIN clients c ON c.id=u.client_id WHERE u.role='client' ORDER BY c.name"),portals:await rows('SELECT pp.* FROM project_portal pp JOIN projects p ON p.id=pp.project_id'),connections:(await rows('SELECT sc.* FROM site_connections sc JOIN projects p ON p.id=sc.project_id')).map(c=>({project_id:c.project_id,...safeConnection(c)}))},{headers:{'Cache-Control':'no-store'}});}catch{return NextResponse.json({error:'تعذر تحميل بوابة العملاء'},{status:503});}}
export async function POST(req:Request){try{if(!sameOrigin(req))return NextResponse.json({error:'طلب غير مسموح'},{status:403});const u=await session();if(!u)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});if(u.role!=='admin')return NextResponse.json({error:'غير مصرح'},{status:403});if(Number(req.headers.get('content-length'))>20000)return NextResponse.json({error:'الطلب كبير جدًا'},{status:413});const b=form.parse(await req.json());
if(b.action==='create'){const client=await one('SELECT * FROM clients WHERE id=?',b.clientId);if(!client)throw new Error('العميل غير موجود');if(await one('SELECT id FROM users WHERE lower(email)=?',b.email))throw new Error('هذا البريد مستخدم بالفعل');const accountId=uid(),salt=uid();await db().batch([stmt("INSERT INTO users(id,name,email,password_hash,salt,role,platform_id,client_id) VALUES(?,?,?,?,?,'client',?,?)",accountId,client.name,b.email,await passwordHash(b.password,salt),salt,'client:'+accountId,client.id),stmt('INSERT INTO audit_logs(id,user_id,entity,record_id,before_json,after_json,created_at) VALUES(?,?,?,?,?,?,?)',uid(),u.id,'clientAccount',accountId,'{}',JSON.stringify({clientId:client.id,email:b.email}),new Date().toISOString())]);return NextResponse.json({ok:true});}
if(b.action==='editAccount'){if(!await one("SELECT id FROM users WHERE id=? AND role='client'",b.id))throw new Error('حساب العميل غير موجود');if(await one('SELECT id FROM users WHERE lower(email)=? AND id<>?',b.email,b.id))throw new Error('هذا البريد مستخدم بالفعل');await db().batch([stmt("UPDATE users SET name=?,email=? WHERE id=? AND role='client'",b.name,b.email,b.id),stmt('DELETE FROM sessions WHERE user_id=?',b.id)]);await audit(u.id,'clientAccount',b.id,{action:b.action,name:b.name,email:b.email});return NextResponse.json({ok:true});}
if(b.action==='resetPassword'||b.action==='setActive'){const account=await one("SELECT id FROM users WHERE id=? AND role='client'",b.id);if(!account)throw new Error('حساب العميل غير موجود');const statements=[];if(b.action==='resetPassword'){const salt=uid();statements.push(stmt("UPDATE users SET password_hash=?,salt=? WHERE id=? AND role='client'",await passwordHash(b.password,salt),salt,b.id));}else statements.push(stmt("UPDATE users SET active=? WHERE id=? AND role='client'",b.active?1:0,b.id));statements.push(stmt('DELETE FROM sessions WHERE user_id=?',b.id));await db().batch(statements);await audit(u.id,'clientAccount',b.id,{action:b.action,...(b.action==='setActive'?{active:b.active}:{})});return NextResponse.json({ok:true});}
const project=await one('SELECT p.id FROM projects p JOIN sales s ON s.id=p.sale_id JOIN clients c ON c.id=s.client_id WHERE p.id=?',b.projectId);if(!project)throw new Error('المشروع غير موجود');
if(b.action==='portal'){const tasks=await rows('SELECT id FROM tasks WHERE project_id=?',b.projectId);if(b.sharedTasks.some(taskId=>!tasks.some(task=>task.id===taskId)))throw new Error('المهمة لا تخص المشروع');await stmt('INSERT INTO project_portal(project_id,preview_url,notes,shared_tasks) VALUES(?,?,?,?) ON CONFLICT(project_id) DO UPDATE SET preview_url=excluded.preview_url,notes=excluded.notes,shared_tasks=excluded.shared_tasks',b.projectId,b.previewUrl,b.notes,JSON.stringify([...new Set(b.sharedTasks)])).run();}
if(b.action==='wordpress'){const key=uid()+uid();await stmt("INSERT INTO site_connections(project_id,provider,site_url,key_hash) VALUES(?,'wordpress',?,?) ON CONFLICT(project_id) DO UPDATE SET provider='wordpress',site_url=excluded.site_url,key_hash=excluded.key_hash,credentials=NULL,payload='{}',last_seen=NULL,last_attempt=0,status='pending',active=1",b.projectId,website(b.siteUrl),await digest(key)).run();await audit(u.id,'siteConnection',b.projectId,{provider:'wordpress',action:'rotate'});return NextResponse.json({ok:true,key},{headers:{'Cache-Control':'no-store'}});}
if(b.action==='shopify'){const domain=shopDomain(b.domain);if(b.mode==='credentials'&&(!b.clientId||!b.clientSecret)||b.mode==='token'&&!b.token)throw new Error('أدخل بيانات التطبيق المطلوبة');const credentials=await encrypt(b.mode==='token'?{token:b.token}:{clientId:b.clientId,clientSecret:b.clientSecret},b.projectId);await stmt("INSERT INTO site_connections(project_id,provider,site_url,credentials) VALUES(?,'shopify',?,?) ON CONFLICT(project_id) DO UPDATE SET provider='shopify',site_url=excluded.site_url,credentials=excluded.credentials,key_hash=NULL,payload='{}',last_seen=NULL,last_attempt=0,status='pending',active=1",b.projectId,domain,credentials).run();}
if(b.action==='revoke')await stmt("UPDATE site_connections SET active=0,key_hash=NULL,credentials=NULL,status='revoked' WHERE project_id=?",b.projectId).run();
if(b.action==='sync')await syncShopify(b.projectId);
await audit(u.id,b.action==='portal'?'projectPortal':'siteConnection',b.projectId,{action:b.action});return NextResponse.json({ok:true});
}catch(e:any){return NextResponse.json({error:e instanceof z.ZodError?'تحقق من الحقول المطلوبة':e.message?.includes('D1')?'تعذر حفظ البيانات':e.message||'تعذر حفظ البيانات'},{status:400});}}
