import {NextResponse} from 'next/server';
import {z} from 'zod';
import {session,sameOrigin} from '../../../lib/auth';
import {rows,one,stmt,db,uid} from '../../../lib/db';
import {id} from '../../../lib/validation';
import {teamRoles,managementRoles,visibleTeamTask,teamWorkData} from '../../../lib/team-work';
import {workStatuses} from '../../../lib/work-access';
const fields={title:z.string().trim().min(1).max(200),description:z.string().trim().max(5000),dueDate:z.union([z.literal(''),z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(d=>!isNaN(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d)]),assigneeId:z.union([id,z.literal('')])};
const form=z.discriminatedUnion('action',[
 z.object({action:z.literal('create'),id,projectId:id,...fields}).strict(),
 z.object({action:z.literal('edit'),id,version:z.number().int().nonnegative(),...fields,status:z.enum(workStatuses)}).strict(),
 z.object({action:z.literal('status'),id,version:z.number().int().nonnegative(),status:z.enum(workStatuses)}).strict(),
 z.object({action:z.literal('delete'),id,version:z.number().int().nonnegative()}).strict(),
 z.object({action:z.literal('projectStatus'),projectId:id,expected:z.string().max(100),status:z.enum(['جديد','قيد التنفيذ','بانتظار العميل','تم التسليم'])}).strict()
]);
export async function GET(req:Request){try{const u=await session();if(!u)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});if(!teamRoles.includes(u.role))return NextResponse.json({error:'غير مصرح'},{status:403});const q=new URL(req.url).searchParams,projectId=q.get('projectId')||'',offset=z.coerce.number().int().min(0).max(100000).parse(q.get('offset')||0);if(projectId)id.parse(projectId);return NextResponse.json(await teamWorkData(u,projectId,offset),{headers:{'Cache-Control':'no-store'}});}catch{return NextResponse.json({error:'تعذر تحميل إدارة الفريق'},{status:400});}}
export async function POST(req:Request){try{if(!sameOrigin(req))return NextResponse.json({error:'طلب غير مسموح'},{status:403});const u=await session();if(!u)return NextResponse.json({error:'يجب تسجيل الدخول'},{status:401});if(!teamRoles.includes(u.role))return NextResponse.json({error:'غير مصرح'},{status:403});const raw=await req.text();if(raw.length>20000)return NextResponse.json({error:'الطلب كبير جدًا'},{status:413});const b=form.parse(JSON.parse(raw)),management=managementRoles.includes(u.role),at=new Date().toISOString();if(!management&&b.action!=='status')return NextResponse.json({error:'غير مصرح'},{status:403});
if(b.action==='projectStatus'){const project=await one('SELECT p.id,s.id AS sale_id,s.status FROM projects p JOIN sales s ON s.id=p.sale_id JOIN clients c ON c.id=s.client_id WHERE p.id=?',b.projectId);if(!project||project.status==='ملغي')return NextResponse.json({error:'المشروع غير متاح'},{status:403});const result=await db().batch([stmt("UPDATE sales SET status=? WHERE id=? AND status=? AND deleted_at IS NULL",b.status,project.sale_id,b.expected),stmt('INSERT INTO audit_logs(id,user_id,entity,record_id,before_json,after_json,created_at) SELECT ?,?,?,?,?,?,? WHERE changes()>0',uid(),u.id,'projectDelivery',b.projectId,JSON.stringify({status:project.status}),JSON.stringify({status:b.status}),at)]);if(!result[0].meta.changes)return NextResponse.json({error:'تغير المشروع؛ حدّث البيانات'},{status:409});return NextResponse.json({ok:true});}
const existing=b.action==='create'?await one('SELECT * FROM team_tasks WHERE id=?',b.id):await visibleTeamTask(b.id,u);
if(b.action!=='create'&&!existing)return NextResponse.json({error:'المهمة غير متاحة لك'},{status:403});
const projectId=b.action==='create'?b.projectId:existing.project_id;
const project=await one('SELECT p.id,s.status FROM projects p JOIN sales s ON s.id=p.sale_id JOIN clients c ON c.id=s.client_id WHERE p.id=?',projectId);if(!project||project.status==='ملغي')return NextResponse.json({error:'المشروع غير متاح'},{status:403});
if(b.action==='create'||b.action==='edit'){if(b.assigneeId&&!await one("SELECT u.id FROM users u JOIN project_members pm ON pm.user_id=u.id WHERE u.id=? AND u.active=1 AND u.role='programmer' AND pm.project_id=?",b.assigneeId,projectId))return NextResponse.json({error:'أسند المشروع للمبرمج أولًا'},{status:400});}
if(b.action==='create'&&existing){if(existing.created_by!==u.id||existing.project_id!==b.projectId||existing.title!==b.title||existing.description!==b.description||existing.assignee_id!==(b.assigneeId||null)||existing.due_date!==b.dueDate||existing.deleted_at)return NextResponse.json({error:'طلب مكرر مختلف'},{status:409});return NextResponse.json({ok:true,id:b.id});}
let update;if(b.action==='create')update=stmt('INSERT INTO team_tasks(id,project_id,assignee_id,created_by,title,description,due_date,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,\'todo\',?,?)',b.id,b.projectId,b.assigneeId||null,u.id,b.title,b.description,b.dueDate,at,at);
else if(b.action==='edit')update=stmt('UPDATE team_tasks SET title=?,description=?,due_date=?,assignee_id=?,status=?,version=version+1,updated_at=? WHERE id=? AND version=? AND deleted_at IS NULL',b.title,b.description,b.dueDate,b.assigneeId||null,b.status,at,b.id,b.version);
else if(b.action==='delete')update=stmt('UPDATE team_tasks SET deleted_at=?,version=version+1,updated_at=? WHERE id=? AND version=? AND deleted_at IS NULL',at,at,b.id,b.version);
else update=stmt(`UPDATE team_tasks SET status=?,version=version+1,updated_at=? WHERE id=? AND version=? AND deleted_at IS NULL AND (?=1 OR (assignee_id=? AND EXISTS(SELECT 1 FROM project_members pm WHERE pm.project_id=team_tasks.project_id AND pm.user_id=?))) AND EXISTS(SELECT 1 FROM projects p JOIN sales s ON s.id=p.sale_id WHERE p.id=team_tasks.project_id AND s.status!='ملغي')`,b.status,at,b.id,b.version,management?1:0,u.id,u.id);
const result=await db().batch([update,stmt('INSERT INTO audit_logs(id,user_id,entity,record_id,before_json,after_json,created_at) SELECT ?,?,?,?,?,?,? WHERE changes()>0',uid(),u.id,'teamTask',b.id,JSON.stringify(existing?{status:existing.status,version:existing.version}:{}),JSON.stringify({action:b.action,projectId,title:'title'in b?b.title:existing.title,status:'status'in b?b.status:'todo',assigneeId:'assigneeId'in b?b.assigneeId:existing?.assignee_id}),at)]);if(!result[0].meta.changes)return NextResponse.json({error:'تغيرت المهمة؛ حدّث البيانات'},{status:409});return NextResponse.json({ok:true,id:b.id});}catch(e){if(!(e instanceof z.ZodError))console.error(e);return NextResponse.json({error:'تعذر حفظ المهمة؛ تحقق من الحقول'},{status:400});}}
